"""init jobs schema fix

Revision ID: 282d89a8fa4d
Revises: 
Create Date: 2026-05-27 02:43:31.551051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '282d89a8fa4d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('url', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('jobs_link_unique'), 'jobs', type_='unique')
    op.drop_column('jobs', 'link')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('link', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('jobs_link_unique'), 'jobs', ['link'], postgresql_nulls_not_distinct=False)
    op.drop_column('jobs', 'created_at')
    op.drop_column('jobs', 'url')
    # ### end Alembic commands ###
