"""create supplier return debit note and credit settlement foundation

Revision ID: 149ed2781959
Revises: 31e6bef1cafa
Create Date: 2026-07-27 18:16:17.172716

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# Revision identifiers used by Alembic.
revision: str = '149ed2781959'
down_revision: Union[str, Sequence[str], None] = '31e6bef1cafa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_returns',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('return_number', sa.String(length=50), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_id', sa.UUID(), nullable=False),
    sa.Column('goods_receipt_id', sa.UUID(), nullable=False),
    sa.Column('source_location_id', sa.UUID(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.Column('reason_code', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('supplier_reference', sa.String(length=150), nullable=True),
    sa.Column('carrier_name', sa.String(length=160), nullable=True),
    sa.Column('tracking_number', sa.String(length=150), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('dispatched_by_user_id', sa.UUID(), nullable=True),
    sa.Column('completed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('cancelled_by_user_id', sa.UUID(), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("\n            (\n                status = 'draft'\n                AND dispatched_at IS NULL\n                AND completed_at IS NULL\n                AND cancelled_at IS NULL\n            )\n            OR\n            (\n                status = 'dispatched'\n                AND dispatched_at IS NOT NULL\n                AND completed_at IS NULL\n                AND cancelled_at IS NULL\n            )\n            OR\n            (\n                status = 'completed'\n                AND dispatched_at IS NOT NULL\n                AND completed_at IS NOT NULL\n                AND cancelled_at IS NULL\n            )\n            OR\n            (\n                status = 'cancelled'\n                AND cancelled_at IS NOT NULL\n                AND cancellation_reason IS NOT NULL\n                AND dispatched_at IS NULL\n                AND completed_at IS NULL\n            )\n            ", name=op.f('ck_supplier_returns_lifecycle_state_valid')),
    sa.CheckConstraint("\n            reason_code IN (\n                'damaged',\n                'defective',\n                'wrong_item',\n                'over_delivery',\n                'quality_failure',\n                'other'\n            )\n            ", name=op.f('ck_supplier_returns_reason_code_valid')),
    sa.CheckConstraint("status IN ('draft', 'dispatched', 'completed', 'cancelled')", name=op.f('ck_supplier_returns_status_valid')),
    sa.ForeignKeyConstraint(['cancelled_by_user_id'], ['users.id'], name=op.f('fk_supplier_returns_cancelled_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['completed_by_user_id'], ['users.id'], name=op.f('fk_supplier_returns_completed_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_supplier_returns_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dispatched_by_user_id'], ['users.id'], name=op.f('fk_supplier_returns_dispatched_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['goods_receipt_id'], ['goods_receipts.id'], name=op.f('fk_supplier_returns_goods_receipt_id_goods_receipts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_supplier_returns_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], name=op.f('fk_supplier_returns_purchase_order_id_purchase_orders'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_location_id'], ['inventory_locations.id'], name=op.f('fk_supplier_returns_source_location_id_inventory_locations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_supplier_returns_supplier_id_suppliers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_returns')),
    sa.UniqueConstraint('organization_id', 'return_number', name='uq_supplier_returns_organization_number')
    )
    op.create_index(op.f('ix_supplier_returns_cancelled_by_user_id'), 'supplier_returns', ['cancelled_by_user_id'], unique=False)
    op.create_index(op.f('ix_supplier_returns_completed_by_user_id'), 'supplier_returns', ['completed_by_user_id'], unique=False)
    op.create_index(op.f('ix_supplier_returns_created_by_user_id'), 'supplier_returns', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_supplier_returns_dispatched_by_user_id'), 'supplier_returns', ['dispatched_by_user_id'], unique=False)
    op.create_index(op.f('ix_supplier_returns_goods_receipt_id'), 'supplier_returns', ['goods_receipt_id'], unique=False)
    op.create_index(op.f('ix_supplier_returns_is_active'), 'supplier_returns', ['is_active'], unique=False)
    op.create_index('ix_supplier_returns_organization_date', 'supplier_returns', ['organization_id', 'return_date'], unique=False)
    op.create_index(op.f('ix_supplier_returns_organization_id'), 'supplier_returns', ['organization_id'], unique=False)
    op.create_index('ix_supplier_returns_organization_receipt', 'supplier_returns', ['organization_id', 'goods_receipt_id'], unique=False)
    op.create_index('ix_supplier_returns_organization_status', 'supplier_returns', ['organization_id', 'status'], unique=False)
    op.create_index('ix_supplier_returns_organization_supplier', 'supplier_returns', ['organization_id', 'supplier_id'], unique=False)
    op.create_index(op.f('ix_supplier_returns_purchase_order_id'), 'supplier_returns', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_supplier_returns_reason_code'), 'supplier_returns', ['reason_code'], unique=False)
    op.create_index(op.f('ix_supplier_returns_return_date'), 'supplier_returns', ['return_date'], unique=False)
    op.create_index(op.f('ix_supplier_returns_source_location_id'), 'supplier_returns', ['source_location_id'], unique=False)
    op.create_index(op.f('ix_supplier_returns_status'), 'supplier_returns', ['status'], unique=False)
    op.create_index(op.f('ix_supplier_returns_supplier_id'), 'supplier_returns', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_supplier_returns_supplier_reference'), 'supplier_returns', ['supplier_reference'], unique=False)
    op.create_index(op.f('ix_supplier_returns_tracking_number'), 'supplier_returns', ['tracking_number'], unique=False)
    op.create_table('supplier_debit_notes',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('debit_note_number', sa.String(length=50), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('supplier_return_id', sa.UUID(), nullable=True),
    sa.Column('purchase_order_id', sa.UUID(), nullable=True),
    sa.Column('note_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'NGN'"), nullable=False),
    sa.Column('supplier_credit_reference', sa.String(length=150), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=16, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=16, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=16, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('issued_by_user_id', sa.UUID(), nullable=True),
    sa.Column('acknowledged_by_user_id', sa.UUID(), nullable=True),
    sa.Column('voided_by_user_id', sa.UUID(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("\n            (\n                status = 'draft'\n                AND issued_at IS NULL\n                AND acknowledged_at IS NULL\n                AND voided_at IS NULL\n            )\n            OR\n            (\n                status = 'issued'\n                AND issued_at IS NOT NULL\n                AND acknowledged_at IS NULL\n                AND voided_at IS NULL\n            )\n            OR\n            (\n                status = 'acknowledged'\n                AND issued_at IS NOT NULL\n                AND acknowledged_at IS NOT NULL\n                AND supplier_credit_reference IS NOT NULL\n                AND voided_at IS NULL\n            )\n            OR\n            (\n                status = 'voided'\n                AND voided_at IS NOT NULL\n                AND void_reason IS NOT NULL\n            )\n            ", name=op.f('ck_supplier_debit_notes_lifecycle_state_valid')),
    sa.CheckConstraint("status IN ('draft', 'issued', 'acknowledged', 'voided')", name=op.f('ck_supplier_debit_notes_status_valid')),
    sa.CheckConstraint('char_length(currency) = 3', name=op.f('ck_supplier_debit_notes_currency_length_valid')),
    sa.CheckConstraint('subtotal >= 0', name=op.f('ck_supplier_debit_notes_subtotal_non_negative')),
    sa.CheckConstraint('tax_total >= 0', name=op.f('ck_supplier_debit_notes_tax_total_non_negative')),
    sa.CheckConstraint('total_amount >= 0', name=op.f('ck_supplier_debit_notes_total_amount_non_negative')),
    sa.ForeignKeyConstraint(['acknowledged_by_user_id'], ['users.id'], name=op.f('fk_supplier_debit_notes_acknowledged_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_supplier_debit_notes_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['issued_by_user_id'], ['users.id'], name=op.f('fk_supplier_debit_notes_issued_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_supplier_debit_notes_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], name=op.f('fk_supplier_debit_notes_purchase_order_id_purchase_orders'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_supplier_debit_notes_supplier_id_suppliers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_return_id'], ['supplier_returns.id'], name=op.f('fk_supplier_debit_notes_supplier_return_id_supplier_returns'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['voided_by_user_id'], ['users.id'], name=op.f('fk_supplier_debit_notes_voided_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_debit_notes')),
    sa.UniqueConstraint('organization_id', 'debit_note_number', name='uq_supplier_debit_notes_organization_number'),
    sa.UniqueConstraint('organization_id', 'supplier_id', 'supplier_credit_reference', name='uq_supplier_debit_notes_supplier_credit_reference')
    )
    op.create_index(op.f('ix_supplier_debit_notes_acknowledged_by_user_id'), 'supplier_debit_notes', ['acknowledged_by_user_id'], unique=False)
    op.create_index(op.f('ix_supplier_debit_notes_created_by_user_id'), 'supplier_debit_notes', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_supplier_debit_notes_currency'), 'supplier_debit_notes', ['currency'], unique=False)
    op.create_index(op.f('ix_supplier_debit_notes_issued_by_user_id'), 'supplier_debit_notes', ['issued_by_user_id'], unique=False)
    op.create_index(op.f('ix_supplier_debit_notes_note_date'), 'supplier_debit_notes', ['note_date'], unique=False)
    op.create_index('ix_supplier_debit_notes_organization_date', 'supplier_debit_notes', ['organization_id', 'note_date'], unique=False)
    op.create_index(op.f('ix_supplier_debit_notes_organization_id'), 'supplier_debit_notes', ['organization_id'], unique=False)
    op.create_index('ix_supplier_debit_notes_organization_return', 'supplier_debit_notes', ['organization_id', 'supplier_return_id'], unique=False)
    op.create_index('ix_supplier_debit_notes_organization_status', 'supplier_debit_notes', ['organization_id', 'status'], unique=False)
    op.create_index('ix_supplier_debit_notes_organization_supplier', 'supplier_debit_notes', ['organization_id', 'supplier_id'], unique=False)
    op.create_index(op.f('ix_supplier_debit_notes_purchase_order_id'), 'supplier_debit_notes', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_supplier_debit_notes_status'), 'supplier_debit_notes', ['status'], unique=False)
    op.create_index(op.f('ix_supplier_debit_notes_supplier_credit_reference'), 'supplier_debit_notes', ['supplier_credit_reference'], unique=False)
    op.create_index(op.f('ix_supplier_debit_notes_supplier_id'), 'supplier_debit_notes', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_supplier_debit_notes_supplier_return_id'), 'supplier_debit_notes', ['supplier_return_id'], unique=False)
    op.create_index(op.f('ix_supplier_debit_notes_voided_by_user_id'), 'supplier_debit_notes', ['voided_by_user_id'], unique=False)
    op.create_table('supplier_return_line_items',
    sa.Column('supplier_return_id', sa.UUID(), nullable=False),
    sa.Column('goods_receipt_line_item_id', sa.UUID(), nullable=False),
    sa.Column('inventory_item_id', sa.UUID(), nullable=True),
    sa.Column('inventory_movement_id', sa.UUID(), nullable=True),
    sa.Column('quantity_source', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity_returned', sa.Numeric(precision=16, scale=3), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=40), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("\n            (\n                quantity_source = 'accepted'\n                AND inventory_item_id IS NOT NULL\n            )\n            OR quantity_source IN ('rejected', 'damaged')\n            ", name=op.f('ck_supplier_return_line_items_accepted_inventory_item_required')),
    sa.CheckConstraint("quantity_source IN ('accepted', 'rejected', 'damaged')", name=op.f('ck_supplier_return_line_items_quantity_source_valid')),
    sa.CheckConstraint('char_length(currency) = 3', name=op.f('ck_supplier_return_line_items_currency_length_valid')),
    sa.CheckConstraint('position >= 0', name=op.f('ck_supplier_return_line_items_position_non_negative')),
    sa.CheckConstraint('quantity_returned > 0', name=op.f('ck_supplier_return_line_items_quantity_returned_positive')),
    sa.CheckConstraint('unit_cost >= 0', name=op.f('ck_supplier_return_line_items_unit_cost_non_negative')),
    sa.ForeignKeyConstraint(['goods_receipt_line_item_id'], ['goods_receipt_line_items.id'], name=op.f('fk_supplier_return_line_items_goods_receipt_line_item_id_goods_receipt_line_items'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], name=op.f('fk_supplier_return_line_items_inventory_item_id_inventory_items'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inventory_movement_id'], ['inventory_movements.id'], name=op.f('fk_supplier_return_line_items_inventory_movement_id_inventory_movements'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_return_id'], ['supplier_returns.id'], name=op.f('fk_supplier_return_line_items_supplier_return_id_supplier_returns'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_return_line_items')),
    sa.UniqueConstraint('inventory_movement_id', name='uq_supplier_return_lines_inventory_movement'),
    sa.UniqueConstraint('supplier_return_id', 'goods_receipt_line_item_id', 'quantity_source', name='uq_supplier_return_lines_receipt_source'),
    sa.UniqueConstraint('supplier_return_id', 'position', name='uq_supplier_return_lines_position')
    )
    op.create_index(op.f('ix_supplier_return_line_items_goods_receipt_line_item_id'), 'supplier_return_line_items', ['goods_receipt_line_item_id'], unique=False)
    op.create_index(op.f('ix_supplier_return_line_items_inventory_item_id'), 'supplier_return_line_items', ['inventory_item_id'], unique=False)
    op.create_index(op.f('ix_supplier_return_line_items_inventory_movement_id'), 'supplier_return_line_items', ['inventory_movement_id'], unique=False)
    op.create_index(op.f('ix_supplier_return_line_items_quantity_source'), 'supplier_return_line_items', ['quantity_source'], unique=False)
    op.create_index(op.f('ix_supplier_return_line_items_supplier_return_id'), 'supplier_return_line_items', ['supplier_return_id'], unique=False)
    op.create_index('ix_supplier_return_lines_receipt_source', 'supplier_return_line_items', ['goods_receipt_line_item_id', 'quantity_source'], unique=False)
    op.create_table('supplier_credit_settlements',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('supplier_debit_note_id', sa.UUID(), nullable=False),
    sa.Column('supplier_payment_id', sa.UUID(), nullable=False),
    sa.Column('amount_settled', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount_settled > 0', name=op.f('ck_supplier_credit_settlements_amount_settled_positive')),
    sa.CheckConstraint('position >= 0', name=op.f('ck_supplier_credit_settlements_position_non_negative')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_supplier_credit_settlements_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_supplier_credit_settlements_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_debit_note_id'], ['supplier_debit_notes.id'], name=op.f('fk_supplier_credit_settlements_supplier_debit_note_id_supplier_debit_notes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_payment_id'], ['supplier_payments.id'], name=op.f('fk_supplier_credit_settlements_supplier_payment_id_supplier_payments'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_credit_settlements')),
    sa.UniqueConstraint('supplier_debit_note_id', 'position', name='uq_supplier_credit_settlements_position'),
    sa.UniqueConstraint('supplier_payment_id', name='uq_supplier_credit_settlements_payment')
    )
    op.create_index(op.f('ix_supplier_credit_settlements_created_by_user_id'), 'supplier_credit_settlements', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_supplier_credit_settlements_organization_id'), 'supplier_credit_settlements', ['organization_id'], unique=False)
    op.create_index('ix_supplier_credit_settlements_organization_note', 'supplier_credit_settlements', ['organization_id', 'supplier_debit_note_id'], unique=False)
    op.create_index(op.f('ix_supplier_credit_settlements_supplier_debit_note_id'), 'supplier_credit_settlements', ['supplier_debit_note_id'], unique=False)
    op.create_index(op.f('ix_supplier_credit_settlements_supplier_payment_id'), 'supplier_credit_settlements', ['supplier_payment_id'], unique=False)
    op.create_table('supplier_debit_note_line_items',
    sa.Column('supplier_debit_note_id', sa.UUID(), nullable=False),
    sa.Column('supplier_return_line_item_id', sa.UUID(), nullable=True),
    sa.Column('supplier_bill_line_item_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=16, scale=3), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=40), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=7, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('line_subtotal', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('line_subtotal >= 0', name=op.f('ck_supplier_debit_note_line_items_line_subtotal_non_negative')),
    sa.CheckConstraint('line_total >= 0', name=op.f('ck_supplier_debit_note_line_items_line_total_non_negative')),
    sa.CheckConstraint('position >= 0', name=op.f('ck_supplier_debit_note_line_items_position_non_negative')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_supplier_debit_note_line_items_quantity_positive')),
    sa.CheckConstraint('tax_amount >= 0', name=op.f('ck_supplier_debit_note_line_items_tax_amount_non_negative')),
    sa.CheckConstraint('tax_rate >= 0 AND tax_rate <= 100', name=op.f('ck_supplier_debit_note_line_items_tax_rate_valid')),
    sa.CheckConstraint('unit_price >= 0', name=op.f('ck_supplier_debit_note_line_items_unit_price_non_negative')),
    sa.ForeignKeyConstraint(['supplier_bill_line_item_id'], ['supplier_bill_line_items.id'], name=op.f('fk_supplier_debit_note_line_items_supplier_bill_line_item_id_supplier_bill_line_items'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_debit_note_id'], ['supplier_debit_notes.id'], name=op.f('fk_supplier_debit_note_line_items_supplier_debit_note_id_supplier_debit_notes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_return_line_item_id'], ['supplier_return_line_items.id'], name=op.f('fk_supplier_debit_note_line_items_supplier_return_line_item_id_supplier_return_line_items'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_debit_note_line_items')),
    sa.UniqueConstraint('supplier_debit_note_id', 'position', name='uq_supplier_debit_note_lines_position')
    )
    op.create_index(op.f('ix_supplier_debit_note_line_items_supplier_bill_line_item_id'), 'supplier_debit_note_line_items', ['supplier_bill_line_item_id'], unique=False)
    op.create_index(op.f('ix_supplier_debit_note_line_items_supplier_debit_note_id'), 'supplier_debit_note_line_items', ['supplier_debit_note_id'], unique=False)
    op.create_index(op.f('ix_supplier_debit_note_line_items_supplier_return_line_item_id'), 'supplier_debit_note_line_items', ['supplier_return_line_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supplier_debit_note_line_items_supplier_return_line_item_id'), table_name='supplier_debit_note_line_items')
    op.drop_index(op.f('ix_supplier_debit_note_line_items_supplier_debit_note_id'), table_name='supplier_debit_note_line_items')
    op.drop_index(op.f('ix_supplier_debit_note_line_items_supplier_bill_line_item_id'), table_name='supplier_debit_note_line_items')
    op.drop_table('supplier_debit_note_line_items')
    op.drop_index(op.f('ix_supplier_credit_settlements_supplier_payment_id'), table_name='supplier_credit_settlements')
    op.drop_index(op.f('ix_supplier_credit_settlements_supplier_debit_note_id'), table_name='supplier_credit_settlements')
    op.drop_index('ix_supplier_credit_settlements_organization_note', table_name='supplier_credit_settlements')
    op.drop_index(op.f('ix_supplier_credit_settlements_organization_id'), table_name='supplier_credit_settlements')
    op.drop_index(op.f('ix_supplier_credit_settlements_created_by_user_id'), table_name='supplier_credit_settlements')
    op.drop_table('supplier_credit_settlements')
    op.drop_index('ix_supplier_return_lines_receipt_source', table_name='supplier_return_line_items')
    op.drop_index(op.f('ix_supplier_return_line_items_supplier_return_id'), table_name='supplier_return_line_items')
    op.drop_index(op.f('ix_supplier_return_line_items_quantity_source'), table_name='supplier_return_line_items')
    op.drop_index(op.f('ix_supplier_return_line_items_inventory_movement_id'), table_name='supplier_return_line_items')
    op.drop_index(op.f('ix_supplier_return_line_items_inventory_item_id'), table_name='supplier_return_line_items')
    op.drop_index(op.f('ix_supplier_return_line_items_goods_receipt_line_item_id'), table_name='supplier_return_line_items')
    op.drop_table('supplier_return_line_items')
    op.drop_index(op.f('ix_supplier_debit_notes_voided_by_user_id'), table_name='supplier_debit_notes')
    op.drop_index(op.f('ix_supplier_debit_notes_supplier_return_id'), table_name='supplier_debit_notes')
    op.drop_index(op.f('ix_supplier_debit_notes_supplier_id'), table_name='supplier_debit_notes')
    op.drop_index(op.f('ix_supplier_debit_notes_supplier_credit_reference'), table_name='supplier_debit_notes')
    op.drop_index(op.f('ix_supplier_debit_notes_status'), table_name='supplier_debit_notes')
    op.drop_index(op.f('ix_supplier_debit_notes_purchase_order_id'), table_name='supplier_debit_notes')
    op.drop_index('ix_supplier_debit_notes_organization_supplier', table_name='supplier_debit_notes')
    op.drop_index('ix_supplier_debit_notes_organization_status', table_name='supplier_debit_notes')
    op.drop_index('ix_supplier_debit_notes_organization_return', table_name='supplier_debit_notes')
    op.drop_index(op.f('ix_supplier_debit_notes_organization_id'), table_name='supplier_debit_notes')
    op.drop_index('ix_supplier_debit_notes_organization_date', table_name='supplier_debit_notes')
    op.drop_index(op.f('ix_supplier_debit_notes_note_date'), table_name='supplier_debit_notes')
    op.drop_index(op.f('ix_supplier_debit_notes_issued_by_user_id'), table_name='supplier_debit_notes')
    op.drop_index(op.f('ix_supplier_debit_notes_currency'), table_name='supplier_debit_notes')
    op.drop_index(op.f('ix_supplier_debit_notes_created_by_user_id'), table_name='supplier_debit_notes')
    op.drop_index(op.f('ix_supplier_debit_notes_acknowledged_by_user_id'), table_name='supplier_debit_notes')
    op.drop_table('supplier_debit_notes')
    op.drop_index(op.f('ix_supplier_returns_tracking_number'), table_name='supplier_returns')
    op.drop_index(op.f('ix_supplier_returns_supplier_reference'), table_name='supplier_returns')
    op.drop_index(op.f('ix_supplier_returns_supplier_id'), table_name='supplier_returns')
    op.drop_index(op.f('ix_supplier_returns_status'), table_name='supplier_returns')
    op.drop_index(op.f('ix_supplier_returns_source_location_id'), table_name='supplier_returns')
    op.drop_index(op.f('ix_supplier_returns_return_date'), table_name='supplier_returns')
    op.drop_index(op.f('ix_supplier_returns_reason_code'), table_name='supplier_returns')
    op.drop_index(op.f('ix_supplier_returns_purchase_order_id'), table_name='supplier_returns')
    op.drop_index('ix_supplier_returns_organization_supplier', table_name='supplier_returns')
    op.drop_index('ix_supplier_returns_organization_status', table_name='supplier_returns')
    op.drop_index('ix_supplier_returns_organization_receipt', table_name='supplier_returns')
    op.drop_index(op.f('ix_supplier_returns_organization_id'), table_name='supplier_returns')
    op.drop_index('ix_supplier_returns_organization_date', table_name='supplier_returns')
    op.drop_index(op.f('ix_supplier_returns_is_active'), table_name='supplier_returns')
    op.drop_index(op.f('ix_supplier_returns_goods_receipt_id'), table_name='supplier_returns')
    op.drop_index(op.f('ix_supplier_returns_dispatched_by_user_id'), table_name='supplier_returns')
    op.drop_index(op.f('ix_supplier_returns_created_by_user_id'), table_name='supplier_returns')
    op.drop_index(op.f('ix_supplier_returns_completed_by_user_id'), table_name='supplier_returns')
    op.drop_index(op.f('ix_supplier_returns_cancelled_by_user_id'), table_name='supplier_returns')
    op.drop_table('supplier_returns')
    # ### end Alembic commands ###
