"""create procurement workflow alert foundation

Revision ID: 31e6bef1cafa
Revises: ce9a5e9fc6dd
Create Date: 2026-07-27 17:27:38.307329

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# Revision identifiers used by Alembic.
revision: str = '31e6bef1cafa'
down_revision: Union[str, Sequence[str], None] = 'ce9a5e9fc6dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procurement_alert_preferences',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('requisition_approval_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('purchase_order_delivery_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('supplier_bill_overdue_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('match_exception_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('payment_action_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('delivery_lead_days', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('payment_lead_days', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('delivery_lead_days >= 0 AND delivery_lead_days <= 30', name=op.f('ck_procurement_alert_preferences_delivery_lead_days_valid')),
    sa.CheckConstraint('payment_lead_days >= 0 AND payment_lead_days <= 30', name=op.f('ck_procurement_alert_preferences_payment_lead_days_valid')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_procurement_alert_preferences_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_procurement_alert_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_procurement_alert_preferences')),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_procurement_alert_preferences_organization_user')
    )
    op.create_index(op.f('ix_procurement_alert_preferences_is_active'), 'procurement_alert_preferences', ['is_active'], unique=False)
    op.create_index('ix_procurement_alert_preferences_organization_active', 'procurement_alert_preferences', ['organization_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_procurement_alert_preferences_organization_id'), 'procurement_alert_preferences', ['organization_id'], unique=False)
    op.create_index(op.f('ix_procurement_alert_preferences_user_id'), 'procurement_alert_preferences', ['user_id'], unique=False)
    op.create_table('procurement_alert_deliveries',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('recipient_user_id', sa.UUID(), nullable=False),
    sa.Column('notification_id', sa.UUID(), nullable=True),
    sa.Column('alert_type', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('alert_date', sa.Date(), nullable=False),
    sa.Column('deduplication_key', sa.String(length=240), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'delivered'"), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("\n            alert_type IN (\n                'requisition_approval_required',\n                'purchase_order_delivery_due',\n                'purchase_order_delivery_overdue',\n                'supplier_bill_overdue',\n                'supplier_bill_match_exception',\n                'supplier_payment_action_required'\n            )\n            ", name=op.f('ck_procurement_alert_deliveries_alert_type_valid')),
    sa.CheckConstraint("status IN ('delivered', 'suppressed', 'failed')", name=op.f('ck_procurement_alert_deliveries_status_valid')),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], name=op.f('fk_procurement_alert_deliveries_notification_id_notifications'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_procurement_alert_deliveries_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], name=op.f('fk_procurement_alert_deliveries_recipient_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_procurement_alert_deliveries')),
    sa.UniqueConstraint('organization_id', 'recipient_user_id', 'deduplication_key', name='uq_procurement_alert_deliveries_dedupe')
    )
    op.create_index(op.f('ix_procurement_alert_deliveries_alert_date'), 'procurement_alert_deliveries', ['alert_date'], unique=False)
    op.create_index(op.f('ix_procurement_alert_deliveries_alert_type'), 'procurement_alert_deliveries', ['alert_type'], unique=False)
    op.create_index(op.f('ix_procurement_alert_deliveries_delivered_at'), 'procurement_alert_deliveries', ['delivered_at'], unique=False)
    op.create_index('ix_procurement_alert_deliveries_entity', 'procurement_alert_deliveries', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_procurement_alert_deliveries_entity_id'), 'procurement_alert_deliveries', ['entity_id'], unique=False)
    op.create_index(op.f('ix_procurement_alert_deliveries_entity_type'), 'procurement_alert_deliveries', ['entity_type'], unique=False)
    op.create_index(op.f('ix_procurement_alert_deliveries_notification_id'), 'procurement_alert_deliveries', ['notification_id'], unique=False)
    op.create_index(op.f('ix_procurement_alert_deliveries_organization_id'), 'procurement_alert_deliveries', ['organization_id'], unique=False)
    op.create_index('ix_procurement_alert_deliveries_organization_recipient', 'procurement_alert_deliveries', ['organization_id', 'recipient_user_id'], unique=False)
    op.create_index('ix_procurement_alert_deliveries_organization_type_date', 'procurement_alert_deliveries', ['organization_id', 'alert_type', 'alert_date'], unique=False)
    op.create_index(op.f('ix_procurement_alert_deliveries_recipient_user_id'), 'procurement_alert_deliveries', ['recipient_user_id'], unique=False)
    op.create_index(op.f('ix_procurement_alert_deliveries_status'), 'procurement_alert_deliveries', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_procurement_alert_deliveries_status'), table_name='procurement_alert_deliveries')
    op.drop_index(op.f('ix_procurement_alert_deliveries_recipient_user_id'), table_name='procurement_alert_deliveries')
    op.drop_index('ix_procurement_alert_deliveries_organization_type_date', table_name='procurement_alert_deliveries')
    op.drop_index('ix_procurement_alert_deliveries_organization_recipient', table_name='procurement_alert_deliveries')
    op.drop_index(op.f('ix_procurement_alert_deliveries_organization_id'), table_name='procurement_alert_deliveries')
    op.drop_index(op.f('ix_procurement_alert_deliveries_notification_id'), table_name='procurement_alert_deliveries')
    op.drop_index(op.f('ix_procurement_alert_deliveries_entity_type'), table_name='procurement_alert_deliveries')
    op.drop_index(op.f('ix_procurement_alert_deliveries_entity_id'), table_name='procurement_alert_deliveries')
    op.drop_index('ix_procurement_alert_deliveries_entity', table_name='procurement_alert_deliveries')
    op.drop_index(op.f('ix_procurement_alert_deliveries_delivered_at'), table_name='procurement_alert_deliveries')
    op.drop_index(op.f('ix_procurement_alert_deliveries_alert_type'), table_name='procurement_alert_deliveries')
    op.drop_index(op.f('ix_procurement_alert_deliveries_alert_date'), table_name='procurement_alert_deliveries')
    op.drop_table('procurement_alert_deliveries')
    op.drop_index(op.f('ix_procurement_alert_preferences_user_id'), table_name='procurement_alert_preferences')
    op.drop_index(op.f('ix_procurement_alert_preferences_organization_id'), table_name='procurement_alert_preferences')
    op.drop_index('ix_procurement_alert_preferences_organization_active', table_name='procurement_alert_preferences')
    op.drop_index(op.f('ix_procurement_alert_preferences_is_active'), table_name='procurement_alert_preferences')
    op.drop_table('procurement_alert_preferences')
    # ### end Alembic commands ###
