"""create assets table

Revision ID: 435be83e2634
Revises: 450f8e984d4e
Create Date: 2026-07-12 18:22:10.258638

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# Revision identifiers used by Alembic.
revision: str = '435be83e2634'
down_revision: Union[str, Sequence[str], None] = '450f8e984d4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('asset_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('asset_type', sa.String(length=40), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('manufacturer', sa.String(length=120), nullable=True),
    sa.Column('model_number', sa.String(length=100), nullable=True),
    sa.Column('serial_number', sa.String(length=120), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('year_of_manufacture', sa.Integer(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('condition', sa.String(length=30), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('last_service_date', sa.Date(), nullable=True),
    sa.Column('next_service_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_assets_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets')),
    sa.UniqueConstraint('organization_id', 'asset_code', name='uq_assets_organization_asset_code'),
    sa.UniqueConstraint('organization_id', 'serial_number', name='uq_assets_organization_serial_number')
    )
    op.create_index(op.f('ix_assets_is_active'), 'assets', ['is_active'], unique=False)
    op.create_index('ix_assets_organization_active', 'assets', ['organization_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_assets_organization_id'), 'assets', ['organization_id'], unique=False)
    op.create_index('ix_assets_organization_name', 'assets', ['organization_id', 'name'], unique=False)
    op.create_index('ix_assets_organization_status', 'assets', ['organization_id', 'status'], unique=False)
    op.create_index('ix_assets_organization_type', 'assets', ['organization_id', 'asset_type'], unique=False)
    op.create_index(op.f('ix_assets_status'), 'assets', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assets_status'), table_name='assets')
    op.drop_index('ix_assets_organization_type', table_name='assets')
    op.drop_index('ix_assets_organization_status', table_name='assets')
    op.drop_index('ix_assets_organization_name', table_name='assets')
    op.drop_index(op.f('ix_assets_organization_id'), table_name='assets')
    op.drop_index('ix_assets_organization_active', table_name='assets')
    op.drop_index(op.f('ix_assets_is_active'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
