"""create workforce profiles table

Revision ID: 450f8e984d4e
Revises: 8375b36db1c4
Create Date: 2026-07-12 16:59:45.005714

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# Revision identifiers used by Alembic.
revision: str = '450f8e984d4e'
down_revision: Union[str, Sequence[str], None] = '8375b36db1c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workforce_profiles',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('membership_id', sa.UUID(), nullable=False),
    sa.Column('employee_code', sa.String(length=50), nullable=True),
    sa.Column('job_title', sa.String(length=120), nullable=True),
    sa.Column('employment_type', sa.String(length=30), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=160), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=50), nullable=True),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('joined_on', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], name=op.f('fk_workforce_profiles_membership_id_memberships'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_workforce_profiles_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workforce_profiles')),
    sa.UniqueConstraint('membership_id', name='uq_workforce_profiles_membership'),
    sa.UniqueConstraint('organization_id', 'employee_code', name='uq_workforce_profiles_organization_employee_code')
    )
    op.create_index(op.f('ix_workforce_profiles_is_active'), 'workforce_profiles', ['is_active'], unique=False)
    op.create_index(op.f('ix_workforce_profiles_is_available'), 'workforce_profiles', ['is_available'], unique=False)
    op.create_index(op.f('ix_workforce_profiles_membership_id'), 'workforce_profiles', ['membership_id'], unique=False)
    op.create_index('ix_workforce_profiles_organization_available', 'workforce_profiles', ['organization_id', 'is_available'], unique=False)
    op.create_index(op.f('ix_workforce_profiles_organization_id'), 'workforce_profiles', ['organization_id'], unique=False)
    op.create_index('ix_workforce_profiles_organization_status', 'workforce_profiles', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_workforce_profiles_status'), 'workforce_profiles', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workforce_profiles_status'), table_name='workforce_profiles')
    op.drop_index('ix_workforce_profiles_organization_status', table_name='workforce_profiles')
    op.drop_index(op.f('ix_workforce_profiles_organization_id'), table_name='workforce_profiles')
    op.drop_index('ix_workforce_profiles_organization_available', table_name='workforce_profiles')
    op.drop_index(op.f('ix_workforce_profiles_membership_id'), table_name='workforce_profiles')
    op.drop_index(op.f('ix_workforce_profiles_is_available'), table_name='workforce_profiles')
    op.drop_index(op.f('ix_workforce_profiles_is_active'), table_name='workforce_profiles')
    op.drop_table('workforce_profiles')
    # ### end Alembic commands ###
