"""create work order expenses

Revision ID: 4fe8c8c8a3f1
Revises: cd108b2ef4f0
Create Date: 2026-07-14 03:33:49.485447

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# Revision identifiers used by Alembic.
revision: str = '4fe8c8c8a3f1'
down_revision: Union[str, Sequence[str], None] = 'cd108b2ef4f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_order_expenses',
    sa.Column('work_order_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=30), server_default='other', nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), server_default='1.000', nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='NGN', nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('vendor_name', sa.String(length=200), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_billable', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('status', sa.String(length=30), server_default='draft', nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("\n            category IN (\n                'labour',\n                'materials',\n                'transport',\n                'equipment',\n                'subcontractor',\n                'permit',\n                'accommodation',\n                'other'\n            )\n            ", name=op.f('ck_work_order_expenses_ck_work_order_expenses_category_valid')),
    sa.CheckConstraint("\n            status IN (\n                'draft',\n                'submitted',\n                'approved',\n                'rejected'\n            )\n            ", name=op.f('ck_work_order_expenses_ck_work_order_expenses_status_valid')),
    sa.CheckConstraint('char_length(currency) = 3', name=op.f('ck_work_order_expenses_ck_work_order_expenses_currency_length')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_work_order_expenses_ck_work_order_expenses_quantity_positive')),
    sa.CheckConstraint('total_amount >= 0', name=op.f('ck_work_order_expenses_ck_work_order_expenses_total_non_negative')),
    sa.CheckConstraint('unit_cost >= 0', name=op.f('ck_work_order_expenses_ck_work_order_expenses_unit_cost_non_negative')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_work_order_expenses_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], name=op.f('fk_work_order_expenses_reviewed_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], name=op.f('fk_work_order_expenses_work_order_id_work_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_order_expenses'))
    )
    op.create_index(op.f('ix_work_order_expenses_category'), 'work_order_expenses', ['category'], unique=False)
    op.create_index(op.f('ix_work_order_expenses_created_by_user_id'), 'work_order_expenses', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_work_order_expenses_currency'), 'work_order_expenses', ['currency'], unique=False)
    op.create_index(op.f('ix_work_order_expenses_expense_date'), 'work_order_expenses', ['expense_date'], unique=False)
    op.create_index(op.f('ix_work_order_expenses_is_active'), 'work_order_expenses', ['is_active'], unique=False)
    op.create_index(op.f('ix_work_order_expenses_is_billable'), 'work_order_expenses', ['is_billable'], unique=False)
    op.create_index(op.f('ix_work_order_expenses_reviewed_by_user_id'), 'work_order_expenses', ['reviewed_by_user_id'], unique=False)
    op.create_index(op.f('ix_work_order_expenses_status'), 'work_order_expenses', ['status'], unique=False)
    op.create_index('ix_work_order_expenses_work_order_active', 'work_order_expenses', ['work_order_id', 'is_active'], unique=False)
    op.create_index('ix_work_order_expenses_work_order_category', 'work_order_expenses', ['work_order_id', 'category'], unique=False)
    op.create_index('ix_work_order_expenses_work_order_date', 'work_order_expenses', ['work_order_id', 'expense_date'], unique=False)
    op.create_index(op.f('ix_work_order_expenses_work_order_id'), 'work_order_expenses', ['work_order_id'], unique=False)
    op.create_index('ix_work_order_expenses_work_order_status', 'work_order_expenses', ['work_order_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_work_order_expenses_work_order_status', table_name='work_order_expenses')
    op.drop_index(op.f('ix_work_order_expenses_work_order_id'), table_name='work_order_expenses')
    op.drop_index('ix_work_order_expenses_work_order_date', table_name='work_order_expenses')
    op.drop_index('ix_work_order_expenses_work_order_category', table_name='work_order_expenses')
    op.drop_index('ix_work_order_expenses_work_order_active', table_name='work_order_expenses')
    op.drop_index(op.f('ix_work_order_expenses_status'), table_name='work_order_expenses')
    op.drop_index(op.f('ix_work_order_expenses_reviewed_by_user_id'), table_name='work_order_expenses')
    op.drop_index(op.f('ix_work_order_expenses_is_billable'), table_name='work_order_expenses')
    op.drop_index(op.f('ix_work_order_expenses_is_active'), table_name='work_order_expenses')
    op.drop_index(op.f('ix_work_order_expenses_expense_date'), table_name='work_order_expenses')
    op.drop_index(op.f('ix_work_order_expenses_currency'), table_name='work_order_expenses')
    op.drop_index(op.f('ix_work_order_expenses_created_by_user_id'), table_name='work_order_expenses')
    op.drop_index(op.f('ix_work_order_expenses_category'), table_name='work_order_expenses')
    op.drop_table('work_order_expenses')
    # ### end Alembic commands ###
