"""create purchase order foundation

Revision ID: 50e1bbf4ff40
Revises: eabe9eac121c
Create Date: 2026-07-27 14:01:53.873179

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# Revision identifiers used by Alembic.
revision: str = '50e1bbf4ff40'
down_revision: Union[str, Sequence[str], None] = 'eabe9eac121c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_orders',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_number', sa.String(length=50), nullable=False),
    sa.Column('source_requisition_id', sa.UUID(), nullable=True),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'NGN'"), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expected_delivery_date', sa.Date(), nullable=True),
    sa.Column('delivery_location_id', sa.UUID(), nullable=True),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('payment_terms_days', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('supplier_reference', sa.String(length=120), nullable=True),
    sa.Column('supplier_name', sa.String(length=180), nullable=False),
    sa.Column('supplier_email', sa.String(length=320), nullable=True),
    sa.Column('supplier_phone', sa.String(length=50), nullable=True),
    sa.Column('supplier_tax_id', sa.String(length=80), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=16, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('discount_total', sa.Numeric(precision=16, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=16, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=16, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('terms_and_conditions', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('issued_by_user_id', sa.UUID(), nullable=True),
    sa.Column('acknowledged_by_user_id', sa.UUID(), nullable=True),
    sa.Column('cancelled_by_user_id', sa.UUID(), nullable=True),
    sa.Column('closed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("\n            status IN (\n                'draft',\n                'issued',\n                'acknowledged',\n                'partially_received',\n                'received',\n                'cancelled',\n                'closed'\n            )\n            ", name=op.f('ck_purchase_orders_status_valid')),
    sa.CheckConstraint('char_length(currency) = 3', name=op.f('ck_purchase_orders_currency_length_valid')),
    sa.CheckConstraint('discount_total >= 0', name=op.f('ck_purchase_orders_discount_total_non_negative')),
    sa.CheckConstraint('payment_terms_days >= 0 AND payment_terms_days <= 3650', name=op.f('ck_purchase_orders_payment_terms_days_valid')),
    sa.CheckConstraint('subtotal >= 0', name=op.f('ck_purchase_orders_subtotal_non_negative')),
    sa.CheckConstraint('tax_total >= 0', name=op.f('ck_purchase_orders_tax_total_non_negative')),
    sa.CheckConstraint('total_amount >= 0', name=op.f('ck_purchase_orders_total_amount_non_negative')),
    sa.ForeignKeyConstraint(['acknowledged_by_user_id'], ['users.id'], name=op.f('fk_purchase_orders_acknowledged_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cancelled_by_user_id'], ['users.id'], name=op.f('fk_purchase_orders_cancelled_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['closed_by_user_id'], ['users.id'], name=op.f('fk_purchase_orders_closed_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_purchase_orders_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['delivery_location_id'], ['inventory_locations.id'], name=op.f('fk_purchase_orders_delivery_location_id_inventory_locations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['issued_by_user_id'], ['users.id'], name=op.f('fk_purchase_orders_issued_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_purchase_orders_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_requisition_id'], ['purchase_requisitions.id'], name=op.f('fk_purchase_orders_source_requisition_id_purchase_requisitions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_purchase_orders_supplier_id_suppliers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_orders')),
    sa.UniqueConstraint('organization_id', 'purchase_order_number', name='uq_purchase_orders_organization_number'),
    sa.UniqueConstraint('organization_id', 'source_requisition_id', name='uq_purchase_orders_organization_requisition')
    )
    op.create_index(op.f('ix_purchase_orders_acknowledged_by_user_id'), 'purchase_orders', ['acknowledged_by_user_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_cancelled_by_user_id'), 'purchase_orders', ['cancelled_by_user_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_closed_by_user_id'), 'purchase_orders', ['closed_by_user_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_created_by_user_id'), 'purchase_orders', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_currency'), 'purchase_orders', ['currency'], unique=False)
    op.create_index(op.f('ix_purchase_orders_delivery_location_id'), 'purchase_orders', ['delivery_location_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_expected_delivery_date'), 'purchase_orders', ['expected_delivery_date'], unique=False)
    op.create_index(op.f('ix_purchase_orders_is_active'), 'purchase_orders', ['is_active'], unique=False)
    op.create_index(op.f('ix_purchase_orders_issue_date'), 'purchase_orders', ['issue_date'], unique=False)
    op.create_index(op.f('ix_purchase_orders_issued_by_user_id'), 'purchase_orders', ['issued_by_user_id'], unique=False)
    op.create_index('ix_purchase_orders_organization_active', 'purchase_orders', ['organization_id', 'is_active'], unique=False)
    op.create_index('ix_purchase_orders_organization_expected_delivery', 'purchase_orders', ['organization_id', 'expected_delivery_date'], unique=False)
    op.create_index(op.f('ix_purchase_orders_organization_id'), 'purchase_orders', ['organization_id'], unique=False)
    op.create_index('ix_purchase_orders_organization_source_requisition', 'purchase_orders', ['organization_id', 'source_requisition_id'], unique=False)
    op.create_index('ix_purchase_orders_organization_status', 'purchase_orders', ['organization_id', 'status'], unique=False)
    op.create_index('ix_purchase_orders_organization_supplier', 'purchase_orders', ['organization_id', 'supplier_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_source_requisition_id'), 'purchase_orders', ['source_requisition_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_status'), 'purchase_orders', ['status'], unique=False)
    op.create_index(op.f('ix_purchase_orders_supplier_id'), 'purchase_orders', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_supplier_reference'), 'purchase_orders', ['supplier_reference'], unique=False)
    op.create_table('purchase_order_line_items',
    sa.Column('purchase_order_id', sa.UUID(), nullable=False),
    sa.Column('source_requisition_line_id', sa.UUID(), nullable=True),
    sa.Column('inventory_item_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity_ordered', sa.Numeric(precision=16, scale=3), server_default=sa.text('1.000'), nullable=False),
    sa.Column('quantity_received', sa.Numeric(precision=16, scale=3), server_default=sa.text('0'), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=40), server_default=sa.text("'each'"), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=16, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=7, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=16, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('line_subtotal', sa.Numeric(precision=16, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=16, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('discount_amount <= line_subtotal', name=op.f('ck_purchase_order_line_items_discount_within_subtotal')),
    sa.CheckConstraint('discount_amount >= 0', name=op.f('ck_purchase_order_line_items_discount_amount_non_negative')),
    sa.CheckConstraint('line_subtotal >= 0', name=op.f('ck_purchase_order_line_items_line_subtotal_non_negative')),
    sa.CheckConstraint('line_total >= 0', name=op.f('ck_purchase_order_line_items_line_total_non_negative')),
    sa.CheckConstraint('position >= 0', name=op.f('ck_purchase_order_line_items_position_non_negative')),
    sa.CheckConstraint('quantity_ordered > 0', name=op.f('ck_purchase_order_line_items_quantity_ordered_positive')),
    sa.CheckConstraint('quantity_received <= quantity_ordered', name=op.f('ck_purchase_order_line_items_quantity_received_within_ordered')),
    sa.CheckConstraint('quantity_received >= 0', name=op.f('ck_purchase_order_line_items_quantity_received_non_negative')),
    sa.CheckConstraint('tax_amount >= 0', name=op.f('ck_purchase_order_line_items_tax_amount_non_negative')),
    sa.CheckConstraint('tax_rate >= 0 AND tax_rate <= 100', name=op.f('ck_purchase_order_line_items_tax_rate_valid')),
    sa.CheckConstraint('unit_price >= 0', name=op.f('ck_purchase_order_line_items_unit_price_non_negative')),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], name=op.f('fk_purchase_order_line_items_inventory_item_id_inventory_items'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], name=op.f('fk_purchase_order_line_items_purchase_order_id_purchase_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_requisition_line_id'], ['purchase_requisition_line_items.id'], name=op.f('fk_purchase_order_line_items_source_requisition_line_id_purchase_requisition_line_items'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_order_line_items')),
    sa.UniqueConstraint('purchase_order_id', 'position', name='uq_purchase_order_lines_position'),
    sa.UniqueConstraint('purchase_order_id', 'source_requisition_line_id', name='uq_purchase_order_lines_requisition_line')
    )
    op.create_index(op.f('ix_purchase_order_line_items_inventory_item_id'), 'purchase_order_line_items', ['inventory_item_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_line_items_purchase_order_id'), 'purchase_order_line_items', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_line_items_source_requisition_line_id'), 'purchase_order_line_items', ['source_requisition_line_id'], unique=False)
    op.create_index('ix_purchase_order_lines_order_item', 'purchase_order_line_items', ['purchase_order_id', 'inventory_item_id'], unique=False)
    op.create_index('ix_purchase_order_lines_order_receipt_progress', 'purchase_order_line_items', ['purchase_order_id', 'quantity_received'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_purchase_order_lines_order_receipt_progress', table_name='purchase_order_line_items')
    op.drop_index('ix_purchase_order_lines_order_item', table_name='purchase_order_line_items')
    op.drop_index(op.f('ix_purchase_order_line_items_source_requisition_line_id'), table_name='purchase_order_line_items')
    op.drop_index(op.f('ix_purchase_order_line_items_purchase_order_id'), table_name='purchase_order_line_items')
    op.drop_index(op.f('ix_purchase_order_line_items_inventory_item_id'), table_name='purchase_order_line_items')
    op.drop_table('purchase_order_line_items')
    op.drop_index(op.f('ix_purchase_orders_supplier_reference'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_supplier_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_status'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_source_requisition_id'), table_name='purchase_orders')
    op.drop_index('ix_purchase_orders_organization_supplier', table_name='purchase_orders')
    op.drop_index('ix_purchase_orders_organization_status', table_name='purchase_orders')
    op.drop_index('ix_purchase_orders_organization_source_requisition', table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_organization_id'), table_name='purchase_orders')
    op.drop_index('ix_purchase_orders_organization_expected_delivery', table_name='purchase_orders')
    op.drop_index('ix_purchase_orders_organization_active', table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_issued_by_user_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_issue_date'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_is_active'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_expected_delivery_date'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_delivery_location_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_currency'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_created_by_user_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_closed_by_user_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_cancelled_by_user_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_acknowledged_by_user_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    # ### end Alembic commands ###
