"""add role uniqueness constraints

Revision ID: 6c302ea99906
Revises: 0d6b5f3f510a
Create Date: 2026-07-11 16:36:25.049512

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# Revision identifiers used by Alembic.
revision: str = '6c302ea99906'
down_revision: Union[str, Sequence[str], None] = '0d6b5f3f510a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_role_permission', 'role_permissions', ['role_id', 'permission_id'])
    op.create_unique_constraint(op.f('uq_roles_name'), 'roles', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_roles_name'), 'roles', type_='unique')
    op.drop_constraint('uq_role_permission', 'role_permissions', type_='unique')
    # ### end Alembic commands ###
