"""
Create invoices, invoice line items, and invoice payments.

Revision ID: 82f6d9e4a1b2
Revises: 4fe8c8c8a3f1
Create Date: 2026-07-14
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


revision: str = "82f6d9e4a1b2"
down_revision: str | None = "4fe8c8c8a3f1"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    """
    Create invoice billing tables.
    """

    op.create_table(
        "invoices",
        sa.Column(
            "organization_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "customer_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "work_order_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "created_by_user_id",
            postgresql.UUID(as_uuid=True),
            nullable=True,
        ),
        sa.Column(
            "issued_by_user_id",
            postgresql.UUID(as_uuid=True),
            nullable=True,
        ),
        sa.Column(
            "voided_by_user_id",
            postgresql.UUID(as_uuid=True),
            nullable=True,
        ),
        sa.Column(
            "invoice_number",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "currency",
            sa.String(length=3),
            server_default="NGN",
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=30),
            server_default="draft",
            nullable=False,
        ),
        sa.Column(
            "invoice_date",
            sa.Date(),
            nullable=False,
        ),
        sa.Column(
            "due_date",
            sa.Date(),
            nullable=True,
        ),
        sa.Column(
            "subtotal",
            sa.Numeric(precision=14, scale=2),
            server_default="0.00",
            nullable=False,
        ),
        sa.Column(
            "discount_amount",
            sa.Numeric(precision=14, scale=2),
            server_default="0.00",
            nullable=False,
        ),
        sa.Column(
            "tax_amount",
            sa.Numeric(precision=14, scale=2),
            server_default="0.00",
            nullable=False,
        ),
        sa.Column(
            "total_amount",
            sa.Numeric(precision=14, scale=2),
            server_default="0.00",
            nullable=False,
        ),
        sa.Column(
            "amount_paid",
            sa.Numeric(precision=14, scale=2),
            server_default="0.00",
            nullable=False,
        ),
        sa.Column(
            "balance_due",
            sa.Numeric(precision=14, scale=2),
            server_default="0.00",
            nullable=False,
        ),
        sa.Column(
            "customer_name",
            sa.String(length=200),
            nullable=False,
        ),
        sa.Column(
            "customer_email",
            sa.String(length=320),
            nullable=True,
        ),
        sa.Column(
            "customer_phone",
            sa.String(length=50),
            nullable=True,
        ),
        sa.Column(
            "billing_address",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "notes",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "terms",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "issued_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "paid_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "voided_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "void_reason",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.CheckConstraint(
            """
            status IN (
                'draft',
                'issued',
                'partially_paid',
                'paid',
                'void'
            )
            """,
            name="ck_invoices_status_valid",
        ),
        sa.CheckConstraint(
            "char_length(currency) = 3",
            name="ck_invoices_currency_length",
        ),
        sa.CheckConstraint(
            "subtotal >= 0",
            name="ck_invoices_subtotal_non_negative",
        ),
        sa.CheckConstraint(
            "discount_amount >= 0",
            name="ck_invoices_discount_non_negative",
        ),
        sa.CheckConstraint(
            "tax_amount >= 0",
            name="ck_invoices_tax_non_negative",
        ),
        sa.CheckConstraint(
            "total_amount >= 0",
            name="ck_invoices_total_non_negative",
        ),
        sa.CheckConstraint(
            "amount_paid >= 0",
            name="ck_invoices_paid_non_negative",
        ),
        sa.CheckConstraint(
            "balance_due >= 0",
            name="ck_invoices_balance_non_negative",
        ),
        sa.CheckConstraint(
            """
            due_date IS NULL
            OR due_date >= invoice_date
            """,
            name="ck_invoices_due_date_valid",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["work_order_id"],
            ["work_orders.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["issued_by_user_id"],
            ["users.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["voided_by_user_id"],
            ["users.id"],
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name="pk_invoices",
        ),
        sa.UniqueConstraint(
            "organization_id",
            "invoice_number",
            name="uq_invoices_organization_number",
        ),
    )

    op.create_index(
        "ix_invoices_organization_status",
        "invoices",
        ["organization_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_invoices_organization_customer",
        "invoices",
        ["organization_id", "customer_id"],
        unique=False,
    )
    op.create_index(
        "ix_invoices_organization_work_order",
        "invoices",
        ["organization_id", "work_order_id"],
        unique=False,
    )
    op.create_index(
        "ix_invoices_organization_currency",
        "invoices",
        ["organization_id", "currency"],
        unique=False,
    )
    op.create_index(
        "ix_invoices_organization_due_date",
        "invoices",
        ["organization_id", "due_date"],
        unique=False,
    )
    op.create_index(
        "ix_invoices_organization_active",
        "invoices",
        ["organization_id", "is_active"],
        unique=False,
    )
    op.create_index(
        "ix_invoices_organization_id",
        "invoices",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_invoices_customer_id",
        "invoices",
        ["customer_id"],
        unique=False,
    )
    op.create_index(
        "ix_invoices_work_order_id",
        "invoices",
        ["work_order_id"],
        unique=False,
    )
    op.create_index(
        "ix_invoices_created_by_user_id",
        "invoices",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        "ix_invoices_issued_by_user_id",
        "invoices",
        ["issued_by_user_id"],
        unique=False,
    )
    op.create_index(
        "ix_invoices_voided_by_user_id",
        "invoices",
        ["voided_by_user_id"],
        unique=False,
    )
    op.create_index(
        "ix_invoices_currency",
        "invoices",
        ["currency"],
        unique=False,
    )
    op.create_index(
        "ix_invoices_status",
        "invoices",
        ["status"],
        unique=False,
    )
    op.create_index(
        "ix_invoices_invoice_date",
        "invoices",
        ["invoice_date"],
        unique=False,
    )
    op.create_index(
        "ix_invoices_due_date",
        "invoices",
        ["due_date"],
        unique=False,
    )
    op.create_index(
        "ix_invoices_is_active",
        "invoices",
        ["is_active"],
        unique=False,
    )

    op.create_table(
        "invoice_line_items",
        sa.Column(
            "invoice_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "work_order_expense_id",
            postgresql.UUID(as_uuid=True),
            nullable=True,
        ),
        sa.Column(
            "source_type",
            sa.String(length=20),
            server_default="manual",
            nullable=False,
        ),
        sa.Column(
            "description",
            sa.String(length=500),
            nullable=False,
        ),
        sa.Column(
            "quantity",
            sa.Numeric(precision=14, scale=3),
            server_default="1.000",
            nullable=False,
        ),
        sa.Column(
            "unit_price",
            sa.Numeric(precision=14, scale=2),
            nullable=False,
        ),
        sa.Column(
            "line_total",
            sa.Numeric(precision=14, scale=2),
            nullable=False,
        ),
        sa.Column(
            "position",
            sa.Integer(),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.CheckConstraint(
            """
            source_type IN (
                'manual',
                'expense'
            )
            """,
            name="ck_invoice_line_items_source_valid",
        ),
        sa.CheckConstraint(
            "quantity > 0",
            name="ck_invoice_line_items_quantity_positive",
        ),
        sa.CheckConstraint(
            "unit_price >= 0",
            name="ck_invoice_line_items_unit_price_non_negative",
        ),
        sa.CheckConstraint(
            "line_total >= 0",
            name="ck_invoice_line_items_total_non_negative",
        ),
        sa.CheckConstraint(
            "position >= 0",
            name="ck_invoice_line_items_position_non_negative",
        ),
        sa.CheckConstraint(
            """
            (
                source_type = 'manual'
                AND work_order_expense_id IS NULL
            )
            OR
            (
                source_type = 'expense'
                AND work_order_expense_id IS NOT NULL
            )
            """,
            name="ck_invoice_line_items_source_expense_match",
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["work_order_expense_id"],
            ["work_order_expenses.id"],
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name="pk_invoice_line_items",
        ),
        sa.UniqueConstraint(
            "invoice_id",
            "position",
            name="uq_invoice_line_items_invoice_position",
        ),
        sa.UniqueConstraint(
            "invoice_id",
            "work_order_expense_id",
            name="uq_invoice_line_items_invoice_expense",
        ),
    )

    op.create_index(
        "ix_invoice_line_items_invoice_active",
        "invoice_line_items",
        ["invoice_id", "is_active"],
        unique=False,
    )
    op.create_index(
        "ix_invoice_line_items_expense",
        "invoice_line_items",
        ["work_order_expense_id"],
        unique=False,
    )
    op.create_index(
        "ix_invoice_line_items_invoice_id",
        "invoice_line_items",
        ["invoice_id"],
        unique=False,
    )
    op.create_index(
        "ix_invoice_line_items_work_order_expense_id",
        "invoice_line_items",
        ["work_order_expense_id"],
        unique=False,
    )
    op.create_index(
        "ix_invoice_line_items_source_type",
        "invoice_line_items",
        ["source_type"],
        unique=False,
    )
    op.create_index(
        "ix_invoice_line_items_is_active",
        "invoice_line_items",
        ["is_active"],
        unique=False,
    )

    op.create_table(
        "invoice_payments",
        sa.Column(
            "invoice_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "recorded_by_user_id",
            postgresql.UUID(as_uuid=True),
            nullable=True,
        ),
        sa.Column(
            "reversed_by_user_id",
            postgresql.UUID(as_uuid=True),
            nullable=True,
        ),
        sa.Column(
            "amount",
            sa.Numeric(precision=14, scale=2),
            nullable=False,
        ),
        sa.Column(
            "currency",
            sa.String(length=3),
            nullable=False,
        ),
        sa.Column(
            "payment_date",
            sa.Date(),
            nullable=False,
        ),
        sa.Column(
            "payment_method",
            sa.String(length=30),
            server_default="bank_transfer",
            nullable=False,
        ),
        sa.Column(
            "reference_number",
            sa.String(length=150),
            nullable=True,
        ),
        sa.Column(
            "notes",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "is_reversed",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "reversed_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "reversal_reason",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.CheckConstraint(
            """
            payment_method IN (
                'cash',
                'bank_transfer',
                'card',
                'mobile_money',
                'cheque',
                'other'
            )
            """,
            name="ck_invoice_payments_method_valid",
        ),
        sa.CheckConstraint(
            "amount > 0",
            name="ck_invoice_payments_amount_positive",
        ),
        sa.CheckConstraint(
            "char_length(currency) = 3",
            name="ck_invoice_payments_currency_length",
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by_user_id"],
            ["users.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["reversed_by_user_id"],
            ["users.id"],
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name="pk_invoice_payments",
        ),
    )

    op.create_index(
        "ix_invoice_payments_invoice_date",
        "invoice_payments",
        ["invoice_id", "payment_date"],
        unique=False,
    )
    op.create_index(
        "ix_invoice_payments_invoice_reversed",
        "invoice_payments",
        ["invoice_id", "is_reversed"],
        unique=False,
    )
    op.create_index(
        "ix_invoice_payments_reference",
        "invoice_payments",
        ["reference_number"],
        unique=False,
    )
    op.create_index(
        "ix_invoice_payments_invoice_id",
        "invoice_payments",
        ["invoice_id"],
        unique=False,
    )
    op.create_index(
        "ix_invoice_payments_recorded_by_user_id",
        "invoice_payments",
        ["recorded_by_user_id"],
        unique=False,
    )
    op.create_index(
        "ix_invoice_payments_reversed_by_user_id",
        "invoice_payments",
        ["reversed_by_user_id"],
        unique=False,
    )
    op.create_index(
        "ix_invoice_payments_currency",
        "invoice_payments",
        ["currency"],
        unique=False,
    )
    op.create_index(
        "ix_invoice_payments_payment_date",
        "invoice_payments",
        ["payment_date"],
        unique=False,
    )
    op.create_index(
        "ix_invoice_payments_payment_method",
        "invoice_payments",
        ["payment_method"],
        unique=False,
    )
    op.create_index(
        "ix_invoice_payments_is_reversed",
        "invoice_payments",
        ["is_reversed"],
        unique=False,
    )


def downgrade() -> None:
    """
    Remove invoice billing tables.
    """

    op.drop_index(
        "ix_invoice_payments_is_reversed",
        table_name="invoice_payments",
    )
    op.drop_index(
        "ix_invoice_payments_payment_method",
        table_name="invoice_payments",
    )
    op.drop_index(
        "ix_invoice_payments_payment_date",
        table_name="invoice_payments",
    )
    op.drop_index(
        "ix_invoice_payments_currency",
        table_name="invoice_payments",
    )
    op.drop_index(
        "ix_invoice_payments_reversed_by_user_id",
        table_name="invoice_payments",
    )
    op.drop_index(
        "ix_invoice_payments_recorded_by_user_id",
        table_name="invoice_payments",
    )
    op.drop_index(
        "ix_invoice_payments_invoice_id",
        table_name="invoice_payments",
    )
    op.drop_index(
        "ix_invoice_payments_reference",
        table_name="invoice_payments",
    )
    op.drop_index(
        "ix_invoice_payments_invoice_reversed",
        table_name="invoice_payments",
    )
    op.drop_index(
        "ix_invoice_payments_invoice_date",
        table_name="invoice_payments",
    )
    op.drop_table("invoice_payments")

    op.drop_index(
        "ix_invoice_line_items_is_active",
        table_name="invoice_line_items",
    )
    op.drop_index(
        "ix_invoice_line_items_source_type",
        table_name="invoice_line_items",
    )
    op.drop_index(
        "ix_invoice_line_items_work_order_expense_id",
        table_name="invoice_line_items",
    )
    op.drop_index(
        "ix_invoice_line_items_invoice_id",
        table_name="invoice_line_items",
    )
    op.drop_index(
        "ix_invoice_line_items_expense",
        table_name="invoice_line_items",
    )
    op.drop_index(
        "ix_invoice_line_items_invoice_active",
        table_name="invoice_line_items",
    )
    op.drop_table("invoice_line_items")

    op.drop_index(
        "ix_invoices_is_active",
        table_name="invoices",
    )
    op.drop_index(
        "ix_invoices_due_date",
        table_name="invoices",
    )
    op.drop_index(
        "ix_invoices_invoice_date",
        table_name="invoices",
    )
    op.drop_index(
        "ix_invoices_status",
        table_name="invoices",
    )
    op.drop_index(
        "ix_invoices_currency",
        table_name="invoices",
    )
    op.drop_index(
        "ix_invoices_voided_by_user_id",
        table_name="invoices",
    )
    op.drop_index(
        "ix_invoices_issued_by_user_id",
        table_name="invoices",
    )
    op.drop_index(
        "ix_invoices_created_by_user_id",
        table_name="invoices",
    )
    op.drop_index(
        "ix_invoices_work_order_id",
        table_name="invoices",
    )
    op.drop_index(
        "ix_invoices_customer_id",
        table_name="invoices",
    )
    op.drop_index(
        "ix_invoices_organization_id",
        table_name="invoices",
    )
    op.drop_index(
        "ix_invoices_organization_active",
        table_name="invoices",
    )
    op.drop_index(
        "ix_invoices_organization_due_date",
        table_name="invoices",
    )
    op.drop_index(
        "ix_invoices_organization_currency",
        table_name="invoices",
    )
    op.drop_index(
        "ix_invoices_organization_work_order",
        table_name="invoices",
    )
    op.drop_index(
        "ix_invoices_organization_customer",
        table_name="invoices",
    )
    op.drop_index(
        "ix_invoices_organization_status",
        table_name="invoices",
    )
    op.drop_table("invoices")