"""create customer sites table

Revision ID: 8375b36db1c4
Revises: 6e83dd165441
Create Date: 2026-07-12 04:35:23.599323

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# Revision identifiers used by Alembic.
revision: str = '8375b36db1c4'
down_revision: Union[str, Sequence[str], None] = '6e83dd165441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_sites',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('site_code', sa.String(length=50), nullable=True),
    sa.Column('site_type', sa.String(length=50), nullable=True),
    sa.Column('contact_name', sa.String(length=160), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address_line_1', sa.String(length=255), nullable=False),
    sa.Column('address_line_2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=30), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('access_instructions', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_customer_sites_customer_id_customers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_customer_sites_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_sites')),
    sa.UniqueConstraint('organization_id', 'site_code', name='uq_customer_sites_organization_site_code')
    )
    op.create_index(op.f('ix_customer_sites_customer_id'), 'customer_sites', ['customer_id'], unique=False)
    op.create_index('ix_customer_sites_customer_name', 'customer_sites', ['customer_id', 'name'], unique=False)
    op.create_index(op.f('ix_customer_sites_is_active'), 'customer_sites', ['is_active'], unique=False)
    op.create_index('ix_customer_sites_organization_active', 'customer_sites', ['organization_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_customer_sites_organization_id'), 'customer_sites', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_sites_organization_id'), table_name='customer_sites')
    op.drop_index('ix_customer_sites_organization_active', table_name='customer_sites')
    op.drop_index(op.f('ix_customer_sites_is_active'), table_name='customer_sites')
    op.drop_index('ix_customer_sites_customer_name', table_name='customer_sites')
    op.drop_index(op.f('ix_customer_sites_customer_id'), table_name='customer_sites')
    op.drop_table('customer_sites')
    # ### end Alembic commands ###
