"""create procurement document versioning and approval evidence foundation

Revision ID: 9904ee90efde
Revises: 149ed2781959
Create Date: 2026-07-27 18:33:27.520752

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# Revision identifiers used by Alembic.
revision: str = '9904ee90efde'
down_revision: Union[str, Sequence[str], None] = '149ed2781959'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procurement_documents',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('document_number', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('required_for_action', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False),
    sa.Column('current_version_number', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('archived_by_user_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archive_reason', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("\n            (\n                status = 'active'\n                AND archived_at IS NULL\n                AND archived_by_user_id IS NULL\n                AND archive_reason IS NULL\n            )\n            OR\n            (\n                status = 'archived'\n                AND archived_at IS NOT NULL\n                AND archive_reason IS NOT NULL\n            )\n            ", name=op.f('ck_procurement_documents_archive_state_valid')),
    sa.CheckConstraint("\n            document_type IN (\n                'supplier_quotation',\n                'requisition_support',\n                'purchase_order',\n                'delivery_note',\n                'goods_receipt_evidence',\n                'supplier_invoice',\n                'payment_evidence',\n                'return_evidence',\n                'debit_note',\n                'supplier_credit_note',\n                'approval_memo',\n                'other'\n            )\n            ", name=op.f('ck_procurement_documents_document_type_valid')),
    sa.CheckConstraint("\n            entity_type IN (\n                'supplier',\n                'purchase_requisition',\n                'purchase_order',\n                'goods_receipt',\n                'supplier_bill',\n                'supplier_payment',\n                'supplier_return',\n                'supplier_debit_note'\n            )\n            ", name=op.f('ck_procurement_documents_entity_type_valid')),
    sa.CheckConstraint("status IN ('active', 'archived')", name=op.f('ck_procurement_documents_status_valid')),
    sa.CheckConstraint('current_version_number >= 0', name=op.f('ck_procurement_documents_current_version_non_negative')),
    sa.ForeignKeyConstraint(['archived_by_user_id'], ['users.id'], name=op.f('fk_procurement_documents_archived_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_procurement_documents_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_procurement_documents_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_procurement_documents')),
    sa.UniqueConstraint('organization_id', 'document_number', name='uq_procurement_documents_organization_number')
    )
    op.create_index(op.f('ix_procurement_documents_archived_at'), 'procurement_documents', ['archived_at'], unique=False)
    op.create_index(op.f('ix_procurement_documents_archived_by_user_id'), 'procurement_documents', ['archived_by_user_id'], unique=False)
    op.create_index(op.f('ix_procurement_documents_created_by_user_id'), 'procurement_documents', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_procurement_documents_document_type'), 'procurement_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_procurement_documents_entity_id'), 'procurement_documents', ['entity_id'], unique=False)
    op.create_index(op.f('ix_procurement_documents_entity_type'), 'procurement_documents', ['entity_type'], unique=False)
    op.create_index('ix_procurement_documents_organization_entity', 'procurement_documents', ['organization_id', 'entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_procurement_documents_organization_id'), 'procurement_documents', ['organization_id'], unique=False)
    op.create_index('ix_procurement_documents_organization_status', 'procurement_documents', ['organization_id', 'status'], unique=False)
    op.create_index('ix_procurement_documents_organization_type', 'procurement_documents', ['organization_id', 'document_type'], unique=False)
    op.create_index(op.f('ix_procurement_documents_required_for_action'), 'procurement_documents', ['required_for_action'], unique=False)
    op.create_index(op.f('ix_procurement_documents_status'), 'procurement_documents', ['status'], unique=False)
    op.create_table('procurement_document_versions',
    sa.Column('procurement_document_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=700), nullable=False),
    sa.Column('content_type', sa.String(length=160), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256_checksum', sa.String(length=64), nullable=False),
    sa.Column('upload_state', sa.String(length=20), server_default=sa.text("'available'"), nullable=False),
    sa.Column('integrity_status', sa.String(length=20), server_default=sa.text("'unverified'"), nullable=False),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=True),
    sa.Column('verified_by_user_id', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("\n            (\n                integrity_status = 'unverified'\n                AND verified_at IS NULL\n                AND verified_by_user_id IS NULL\n            )\n            OR\n            (\n                integrity_status IN ('verified', 'mismatch')\n                AND verified_at IS NOT NULL\n            )\n            ", name=op.f('ck_procurement_document_versions_verification_state_valid')),
    sa.CheckConstraint("\n            integrity_status IN (\n                'unverified',\n                'verified',\n                'mismatch'\n            )\n            ", name=op.f('ck_procurement_document_versions_integrity_status_valid')),
    sa.CheckConstraint("\n            upload_state IN (\n                'available',\n                'quarantined',\n                'failed'\n            )\n            ", name=op.f('ck_procurement_document_versions_upload_state_valid')),
    sa.CheckConstraint('char_length(sha256_checksum) = 64', name=op.f('ck_procurement_document_versions_sha256_length_valid')),
    sa.CheckConstraint('file_size_bytes > 0 AND file_size_bytes <= 26214400', name=op.f('ck_procurement_document_versions_file_size_valid')),
    sa.CheckConstraint('version_number > 0', name=op.f('ck_procurement_document_versions_version_number_positive')),
    sa.ForeignKeyConstraint(['procurement_document_id'], ['procurement_documents.id'], name=op.f('fk_procurement_document_versions_procurement_document_id_procurement_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], name=op.f('fk_procurement_document_versions_uploaded_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], name=op.f('fk_procurement_document_versions_verified_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_procurement_document_versions')),
    sa.UniqueConstraint('procurement_document_id', 'version_number', name='uq_procurement_document_versions_number'),
    sa.UniqueConstraint('storage_key', name='uq_procurement_document_versions_storage_key')
    )
    op.create_index(op.f('ix_procurement_document_versions_content_type'), 'procurement_document_versions', ['content_type'], unique=False)
    op.create_index('ix_procurement_document_versions_document_state', 'procurement_document_versions', ['procurement_document_id', 'upload_state', 'integrity_status'], unique=False)
    op.create_index(op.f('ix_procurement_document_versions_integrity_status'), 'procurement_document_versions', ['integrity_status'], unique=False)
    op.create_index(op.f('ix_procurement_document_versions_procurement_document_id'), 'procurement_document_versions', ['procurement_document_id'], unique=False)
    op.create_index(op.f('ix_procurement_document_versions_sha256_checksum'), 'procurement_document_versions', ['sha256_checksum'], unique=False)
    op.create_index(op.f('ix_procurement_document_versions_upload_state'), 'procurement_document_versions', ['upload_state'], unique=False)
    op.create_index(op.f('ix_procurement_document_versions_uploaded_by_user_id'), 'procurement_document_versions', ['uploaded_by_user_id'], unique=False)
    op.create_index(op.f('ix_procurement_document_versions_verified_at'), 'procurement_document_versions', ['verified_at'], unique=False)
    op.create_index(op.f('ix_procurement_document_versions_verified_by_user_id'), 'procurement_document_versions', ['verified_by_user_id'], unique=False)
    op.create_table('procurement_approval_evidence',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=60), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('procurement_document_version_id', sa.UUID(), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_membership_id', sa.UUID(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('evidence_hash', sa.String(length=64), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("\n            action_type IN (\n                'requisition_approval',\n                'purchase_order_issue',\n                'goods_receipt_posting',\n                'supplier_bill_approval',\n                'supplier_payment_posting',\n                'supplier_return_dispatch',\n                'debit_note_issue',\n                'credit_settlement',\n                'exception_waiver'\n            )\n            ", name=op.f('ck_procurement_approval_evidence_action_type_valid')),
    sa.CheckConstraint("\n            decision IN (\n                'approved',\n                'acknowledged',\n                'rejected',\n                'waived'\n            )\n            ", name=op.f('ck_procurement_approval_evidence_decision_valid')),
    sa.CheckConstraint("\n            entity_type IN (\n                'purchase_requisition',\n                'purchase_order',\n                'goods_receipt',\n                'supplier_bill',\n                'supplier_payment',\n                'supplier_return',\n                'supplier_debit_note'\n            )\n            ", name=op.f('ck_procurement_approval_evidence_entity_type_valid')),
    sa.CheckConstraint('char_length(evidence_hash) = 64', name=op.f('ck_procurement_approval_evidence_evidence_hash_length_valid')),
    sa.ForeignKeyConstraint(['actor_membership_id'], ['memberships.id'], name=op.f('fk_procurement_approval_evidence_actor_membership_id_memberships'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_procurement_approval_evidence_actor_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_procurement_approval_evidence_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['procurement_document_version_id'], ['procurement_document_versions.id'], name=op.f('fk_procurement_approval_evidence_procurement_document_version_id_procurement_document_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_procurement_approval_evidence')),
    sa.UniqueConstraint('organization_id', 'evidence_hash', name='uq_procurement_approval_evidence_hash')
    )
    op.create_index(op.f('ix_procurement_approval_evidence_action_type'), 'procurement_approval_evidence', ['action_type'], unique=False)
    op.create_index(op.f('ix_procurement_approval_evidence_actor_membership_id'), 'procurement_approval_evidence', ['actor_membership_id'], unique=False)
    op.create_index(op.f('ix_procurement_approval_evidence_actor_user_id'), 'procurement_approval_evidence', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_procurement_approval_evidence_decision'), 'procurement_approval_evidence', ['decision'], unique=False)
    op.create_index(op.f('ix_procurement_approval_evidence_entity_id'), 'procurement_approval_evidence', ['entity_id'], unique=False)
    op.create_index(op.f('ix_procurement_approval_evidence_entity_type'), 'procurement_approval_evidence', ['entity_type'], unique=False)
    op.create_index(op.f('ix_procurement_approval_evidence_occurred_at'), 'procurement_approval_evidence', ['occurred_at'], unique=False)
    op.create_index('ix_procurement_approval_evidence_organization_action', 'procurement_approval_evidence', ['organization_id', 'action_type', 'occurred_at'], unique=False)
    op.create_index('ix_procurement_approval_evidence_organization_entity', 'procurement_approval_evidence', ['organization_id', 'entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_procurement_approval_evidence_organization_id'), 'procurement_approval_evidence', ['organization_id'], unique=False)
    op.create_index(op.f('ix_procurement_approval_evidence_procurement_document_version_id'), 'procurement_approval_evidence', ['procurement_document_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_procurement_approval_evidence_procurement_document_version_id'), table_name='procurement_approval_evidence')
    op.drop_index(op.f('ix_procurement_approval_evidence_organization_id'), table_name='procurement_approval_evidence')
    op.drop_index('ix_procurement_approval_evidence_organization_entity', table_name='procurement_approval_evidence')
    op.drop_index('ix_procurement_approval_evidence_organization_action', table_name='procurement_approval_evidence')
    op.drop_index(op.f('ix_procurement_approval_evidence_occurred_at'), table_name='procurement_approval_evidence')
    op.drop_index(op.f('ix_procurement_approval_evidence_entity_type'), table_name='procurement_approval_evidence')
    op.drop_index(op.f('ix_procurement_approval_evidence_entity_id'), table_name='procurement_approval_evidence')
    op.drop_index(op.f('ix_procurement_approval_evidence_decision'), table_name='procurement_approval_evidence')
    op.drop_index(op.f('ix_procurement_approval_evidence_actor_user_id'), table_name='procurement_approval_evidence')
    op.drop_index(op.f('ix_procurement_approval_evidence_actor_membership_id'), table_name='procurement_approval_evidence')
    op.drop_index(op.f('ix_procurement_approval_evidence_action_type'), table_name='procurement_approval_evidence')
    op.drop_table('procurement_approval_evidence')
    op.drop_index(op.f('ix_procurement_document_versions_verified_by_user_id'), table_name='procurement_document_versions')
    op.drop_index(op.f('ix_procurement_document_versions_verified_at'), table_name='procurement_document_versions')
    op.drop_index(op.f('ix_procurement_document_versions_uploaded_by_user_id'), table_name='procurement_document_versions')
    op.drop_index(op.f('ix_procurement_document_versions_upload_state'), table_name='procurement_document_versions')
    op.drop_index(op.f('ix_procurement_document_versions_sha256_checksum'), table_name='procurement_document_versions')
    op.drop_index(op.f('ix_procurement_document_versions_procurement_document_id'), table_name='procurement_document_versions')
    op.drop_index(op.f('ix_procurement_document_versions_integrity_status'), table_name='procurement_document_versions')
    op.drop_index('ix_procurement_document_versions_document_state', table_name='procurement_document_versions')
    op.drop_index(op.f('ix_procurement_document_versions_content_type'), table_name='procurement_document_versions')
    op.drop_table('procurement_document_versions')
    op.drop_index(op.f('ix_procurement_documents_status'), table_name='procurement_documents')
    op.drop_index(op.f('ix_procurement_documents_required_for_action'), table_name='procurement_documents')
    op.drop_index('ix_procurement_documents_organization_type', table_name='procurement_documents')
    op.drop_index('ix_procurement_documents_organization_status', table_name='procurement_documents')
    op.drop_index(op.f('ix_procurement_documents_organization_id'), table_name='procurement_documents')
    op.drop_index('ix_procurement_documents_organization_entity', table_name='procurement_documents')
    op.drop_index(op.f('ix_procurement_documents_entity_type'), table_name='procurement_documents')
    op.drop_index(op.f('ix_procurement_documents_entity_id'), table_name='procurement_documents')
    op.drop_index(op.f('ix_procurement_documents_document_type'), table_name='procurement_documents')
    op.drop_index(op.f('ix_procurement_documents_created_by_user_id'), table_name='procurement_documents')
    op.drop_index(op.f('ix_procurement_documents_archived_by_user_id'), table_name='procurement_documents')
    op.drop_index(op.f('ix_procurement_documents_archived_at'), table_name='procurement_documents')
    op.drop_table('procurement_documents')
    # ### end Alembic commands ###
