"""create supplier foundation

Revision ID: b09ec732449f
Revises: d8ceb56a8f4f
Create Date: 2026-07-27 02:32:04.651648

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# Revision identifiers used by Alembic.
revision: str = 'b09ec732449f'
down_revision: Union[str, Sequence[str], None] = 'd8ceb56a8f4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('supplier_type', sa.String(length=30), server_default=sa.text("'company'"), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('contact_name', sa.String(length=160), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('alternate_phone', sa.String(length=50), nullable=True),
    sa.Column('tax_id', sa.String(length=80), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('payment_terms_days', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'NGN'"), nullable=False),
    sa.Column('address_line_1', sa.String(length=255), nullable=True),
    sa.Column('address_line_2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=30), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("supplier_type IN ('company', 'individual')", name=op.f('ck_suppliers_type_valid')),
    sa.CheckConstraint('char_length(currency) = 3', name=op.f('ck_suppliers_currency_length_valid')),
    sa.CheckConstraint('payment_terms_days >= 0 AND payment_terms_days <= 3650', name=op.f('ck_suppliers_payment_terms_days_valid')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_suppliers_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers')),
    sa.UniqueConstraint('organization_id', 'code', name='uq_suppliers_organization_code'),
    sa.UniqueConstraint('organization_id', 'registration_number', name='uq_suppliers_organization_registration_number'),
    sa.UniqueConstraint('organization_id', 'tax_id', name='uq_suppliers_organization_tax_id')
    )
    op.create_index(op.f('ix_suppliers_category'), 'suppliers', ['category'], unique=False)
    op.create_index(op.f('ix_suppliers_email'), 'suppliers', ['email'], unique=False)
    op.create_index(op.f('ix_suppliers_is_active'), 'suppliers', ['is_active'], unique=False)
    op.create_index('ix_suppliers_organization_active', 'suppliers', ['organization_id', 'is_active'], unique=False)
    op.create_index('ix_suppliers_organization_category', 'suppliers', ['organization_id', 'category'], unique=False)
    op.create_index(op.f('ix_suppliers_organization_id'), 'suppliers', ['organization_id'], unique=False)
    op.create_index('ix_suppliers_organization_name', 'suppliers', ['organization_id', 'name'], unique=False)
    op.create_index('ix_suppliers_organization_type', 'suppliers', ['organization_id', 'supplier_type'], unique=False)
    op.create_index(op.f('ix_suppliers_supplier_type'), 'suppliers', ['supplier_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suppliers_supplier_type'), table_name='suppliers')
    op.drop_index('ix_suppliers_organization_type', table_name='suppliers')
    op.drop_index('ix_suppliers_organization_name', table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_organization_id'), table_name='suppliers')
    op.drop_index('ix_suppliers_organization_category', table_name='suppliers')
    op.drop_index('ix_suppliers_organization_active', table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_is_active'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_email'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_category'), table_name='suppliers')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
