"""create goods receipt foundation

Revision ID: b1859e807f6e
Revises: 50e1bbf4ff40
Create Date: 2026-07-27 14:31:45.815558

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# Revision identifiers used by Alembic.
revision: str = 'b1859e807f6e'
down_revision: Union[str, Sequence[str], None] = '50e1bbf4ff40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goods_receipts',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('goods_receipt_number', sa.String(length=50), nullable=False),
    sa.Column('purchase_order_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('receiving_location_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('supplier_delivery_note', sa.String(length=120), nullable=True),
    sa.Column('carrier_name', sa.String(length=160), nullable=True),
    sa.Column('vehicle_reference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('posted_by_user_id', sa.UUID(), nullable=True),
    sa.Column('cancelled_by_user_id', sa.UUID(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'posted', 'cancelled')", name=op.f('ck_goods_receipts_status_valid')),
    sa.ForeignKeyConstraint(['cancelled_by_user_id'], ['users.id'], name=op.f('fk_goods_receipts_cancelled_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_goods_receipts_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_goods_receipts_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['posted_by_user_id'], ['users.id'], name=op.f('fk_goods_receipts_posted_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], name=op.f('fk_goods_receipts_purchase_order_id_purchase_orders'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['receiving_location_id'], ['inventory_locations.id'], name=op.f('fk_goods_receipts_receiving_location_id_inventory_locations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_goods_receipts_supplier_id_suppliers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goods_receipts')),
    sa.UniqueConstraint('organization_id', 'goods_receipt_number', name='uq_goods_receipts_organization_number')
    )
    op.create_index(op.f('ix_goods_receipts_cancelled_by_user_id'), 'goods_receipts', ['cancelled_by_user_id'], unique=False)
    op.create_index(op.f('ix_goods_receipts_created_by_user_id'), 'goods_receipts', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_goods_receipts_is_active'), 'goods_receipts', ['is_active'], unique=False)
    op.create_index('ix_goods_receipts_organization_active', 'goods_receipts', ['organization_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_goods_receipts_organization_id'), 'goods_receipts', ['organization_id'], unique=False)
    op.create_index('ix_goods_receipts_organization_location', 'goods_receipts', ['organization_id', 'receiving_location_id'], unique=False)
    op.create_index('ix_goods_receipts_organization_purchase_order', 'goods_receipts', ['organization_id', 'purchase_order_id'], unique=False)
    op.create_index('ix_goods_receipts_organization_received_at', 'goods_receipts', ['organization_id', 'received_at'], unique=False)
    op.create_index('ix_goods_receipts_organization_status', 'goods_receipts', ['organization_id', 'status'], unique=False)
    op.create_index('ix_goods_receipts_organization_supplier', 'goods_receipts', ['organization_id', 'supplier_id'], unique=False)
    op.create_index(op.f('ix_goods_receipts_posted_by_user_id'), 'goods_receipts', ['posted_by_user_id'], unique=False)
    op.create_index(op.f('ix_goods_receipts_purchase_order_id'), 'goods_receipts', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_goods_receipts_received_at'), 'goods_receipts', ['received_at'], unique=False)
    op.create_index(op.f('ix_goods_receipts_receiving_location_id'), 'goods_receipts', ['receiving_location_id'], unique=False)
    op.create_index(op.f('ix_goods_receipts_status'), 'goods_receipts', ['status'], unique=False)
    op.create_index(op.f('ix_goods_receipts_supplier_delivery_note'), 'goods_receipts', ['supplier_delivery_note'], unique=False)
    op.create_index(op.f('ix_goods_receipts_supplier_id'), 'goods_receipts', ['supplier_id'], unique=False)
    op.create_table('goods_receipt_line_items',
    sa.Column('goods_receipt_id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_line_item_id', sa.UUID(), nullable=False),
    sa.Column('inventory_item_id', sa.UUID(), nullable=True),
    sa.Column('inventory_movement_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity_accepted', sa.Numeric(precision=16, scale=3), server_default=sa.text('0'), nullable=False),
    sa.Column('quantity_rejected', sa.Numeric(precision=16, scale=3), server_default=sa.text('0'), nullable=False),
    sa.Column('quantity_damaged', sa.Numeric(precision=16, scale=3), server_default=sa.text('0'), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=40), server_default=sa.text("'each'"), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'NGN'"), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('damage_notes', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('char_length(currency) = 3', name=op.f('ck_goods_receipt_line_items_currency_length_valid')),
    sa.CheckConstraint('position >= 0', name=op.f('ck_goods_receipt_line_items_position_non_negative')),
    sa.CheckConstraint('quantity_accepted + quantity_rejected + quantity_damaged > 0', name=op.f('ck_goods_receipt_line_items_delivered_quantity_positive')),
    sa.CheckConstraint('quantity_accepted >= 0', name=op.f('ck_goods_receipt_line_items_accepted_non_negative')),
    sa.CheckConstraint('quantity_damaged >= 0', name=op.f('ck_goods_receipt_line_items_damaged_non_negative')),
    sa.CheckConstraint('quantity_rejected >= 0', name=op.f('ck_goods_receipt_line_items_rejected_non_negative')),
    sa.CheckConstraint('unit_cost >= 0', name=op.f('ck_goods_receipt_line_items_unit_cost_non_negative')),
    sa.ForeignKeyConstraint(['goods_receipt_id'], ['goods_receipts.id'], name=op.f('fk_goods_receipt_line_items_goods_receipt_id_goods_receipts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], name=op.f('fk_goods_receipt_line_items_inventory_item_id_inventory_items'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inventory_movement_id'], ['inventory_movements.id'], name=op.f('fk_goods_receipt_line_items_inventory_movement_id_inventory_movements'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['purchase_order_line_item_id'], ['purchase_order_line_items.id'], name=op.f('fk_goods_receipt_line_items_purchase_order_line_item_id_purchase_order_line_items'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goods_receipt_line_items')),
    sa.UniqueConstraint('goods_receipt_id', 'position', name='uq_goods_receipt_lines_position'),
    sa.UniqueConstraint('goods_receipt_id', 'purchase_order_line_item_id', name='uq_goods_receipt_lines_purchase_order_line'),
    sa.UniqueConstraint('inventory_movement_id', name='uq_goods_receipt_lines_inventory_movement')
    )
    op.create_index(op.f('ix_goods_receipt_line_items_goods_receipt_id'), 'goods_receipt_line_items', ['goods_receipt_id'], unique=False)
    op.create_index(op.f('ix_goods_receipt_line_items_inventory_item_id'), 'goods_receipt_line_items', ['inventory_item_id'], unique=False)
    op.create_index(op.f('ix_goods_receipt_line_items_inventory_movement_id'), 'goods_receipt_line_items', ['inventory_movement_id'], unique=False)
    op.create_index(op.f('ix_goods_receipt_line_items_purchase_order_line_item_id'), 'goods_receipt_line_items', ['purchase_order_line_item_id'], unique=False)
    op.create_index('ix_goods_receipt_lines_receipt_inventory_item', 'goods_receipt_line_items', ['goods_receipt_id', 'inventory_item_id'], unique=False)
    op.create_index('ix_goods_receipt_lines_receipt_order_line', 'goods_receipt_line_items', ['goods_receipt_id', 'purchase_order_line_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_goods_receipt_lines_receipt_order_line', table_name='goods_receipt_line_items')
    op.drop_index('ix_goods_receipt_lines_receipt_inventory_item', table_name='goods_receipt_line_items')
    op.drop_index(op.f('ix_goods_receipt_line_items_purchase_order_line_item_id'), table_name='goods_receipt_line_items')
    op.drop_index(op.f('ix_goods_receipt_line_items_inventory_movement_id'), table_name='goods_receipt_line_items')
    op.drop_index(op.f('ix_goods_receipt_line_items_inventory_item_id'), table_name='goods_receipt_line_items')
    op.drop_index(op.f('ix_goods_receipt_line_items_goods_receipt_id'), table_name='goods_receipt_line_items')
    op.drop_table('goods_receipt_line_items')
    op.drop_index(op.f('ix_goods_receipts_supplier_id'), table_name='goods_receipts')
    op.drop_index(op.f('ix_goods_receipts_supplier_delivery_note'), table_name='goods_receipts')
    op.drop_index(op.f('ix_goods_receipts_status'), table_name='goods_receipts')
    op.drop_index(op.f('ix_goods_receipts_receiving_location_id'), table_name='goods_receipts')
    op.drop_index(op.f('ix_goods_receipts_received_at'), table_name='goods_receipts')
    op.drop_index(op.f('ix_goods_receipts_purchase_order_id'), table_name='goods_receipts')
    op.drop_index(op.f('ix_goods_receipts_posted_by_user_id'), table_name='goods_receipts')
    op.drop_index('ix_goods_receipts_organization_supplier', table_name='goods_receipts')
    op.drop_index('ix_goods_receipts_organization_status', table_name='goods_receipts')
    op.drop_index('ix_goods_receipts_organization_received_at', table_name='goods_receipts')
    op.drop_index('ix_goods_receipts_organization_purchase_order', table_name='goods_receipts')
    op.drop_index('ix_goods_receipts_organization_location', table_name='goods_receipts')
    op.drop_index(op.f('ix_goods_receipts_organization_id'), table_name='goods_receipts')
    op.drop_index('ix_goods_receipts_organization_active', table_name='goods_receipts')
    op.drop_index(op.f('ix_goods_receipts_is_active'), table_name='goods_receipts')
    op.drop_index(op.f('ix_goods_receipts_created_by_user_id'), table_name='goods_receipts')
    op.drop_index(op.f('ix_goods_receipts_cancelled_by_user_id'), table_name='goods_receipts')
    op.drop_table('goods_receipts')
    # ### end Alembic commands ###
