"""create work order notes and attachments

Revision ID: cd108b2ef4f0
Revises: ebb5dd8c761e
Create Date: 2026-07-14 01:50:57.087882

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# Revision identifiers used by Alembic.
revision: str = 'cd108b2ef4f0'
down_revision: Union[str, Sequence[str], None] = 'ebb5dd8c761e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_order_notes',
    sa.Column('work_order_id', sa.UUID(), nullable=False),
    sa.Column('author_user_id', sa.UUID(), nullable=True),
    sa.Column('note_type', sa.String(length=30), server_default='note', nullable=False),
    sa.Column('visibility', sa.String(length=30), server_default='internal', nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("note_type IN ('note', 'field_update')", name=op.f('ck_work_order_notes_ck_work_order_notes_type_valid')),
    sa.CheckConstraint("visibility IN ('internal', 'customer')", name=op.f('ck_work_order_notes_ck_work_order_notes_visibility_valid')),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], name=op.f('fk_work_order_notes_author_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], name=op.f('fk_work_order_notes_work_order_id_work_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_order_notes'))
    )
    op.create_index(op.f('ix_work_order_notes_author_user_id'), 'work_order_notes', ['author_user_id'], unique=False)
    op.create_index(op.f('ix_work_order_notes_is_active'), 'work_order_notes', ['is_active'], unique=False)
    op.create_index(op.f('ix_work_order_notes_is_pinned'), 'work_order_notes', ['is_pinned'], unique=False)
    op.create_index(op.f('ix_work_order_notes_note_type'), 'work_order_notes', ['note_type'], unique=False)
    op.create_index(op.f('ix_work_order_notes_visibility'), 'work_order_notes', ['visibility'], unique=False)
    op.create_index('ix_work_order_notes_work_order_active', 'work_order_notes', ['work_order_id', 'is_active'], unique=False)
    op.create_index('ix_work_order_notes_work_order_created', 'work_order_notes', ['work_order_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_work_order_notes_work_order_id'), 'work_order_notes', ['work_order_id'], unique=False)
    op.create_index('ix_work_order_notes_work_order_visibility', 'work_order_notes', ['work_order_id', 'visibility'], unique=False)
    op.create_table('work_order_note_attachments',
    sa.Column('note_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=150), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('file_size_bytes >= 0', name=op.f('ck_work_order_note_attachments_ck_work_order_note_attachments_size_non_negative')),
    sa.CheckConstraint('position >= 0', name=op.f('ck_work_order_note_attachments_ck_work_order_note_attachments_position_non_negative')),
    sa.ForeignKeyConstraint(['note_id'], ['work_order_notes.id'], name=op.f('fk_work_order_note_attachments_note_id_work_order_notes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_order_note_attachments'))
    )
    op.create_index(op.f('ix_work_order_note_attachments_note_id'), 'work_order_note_attachments', ['note_id'], unique=False)
    op.create_index('ix_work_order_note_attachments_note_position', 'work_order_note_attachments', ['note_id', 'position'], unique=False)
    op.create_index(op.f('ix_work_order_note_attachments_storage_key'), 'work_order_note_attachments', ['storage_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_order_note_attachments_storage_key'), table_name='work_order_note_attachments')
    op.drop_index('ix_work_order_note_attachments_note_position', table_name='work_order_note_attachments')
    op.drop_index(op.f('ix_work_order_note_attachments_note_id'), table_name='work_order_note_attachments')
    op.drop_table('work_order_note_attachments')
    op.drop_index('ix_work_order_notes_work_order_visibility', table_name='work_order_notes')
    op.drop_index(op.f('ix_work_order_notes_work_order_id'), table_name='work_order_notes')
    op.drop_index('ix_work_order_notes_work_order_created', table_name='work_order_notes')
    op.drop_index('ix_work_order_notes_work_order_active', table_name='work_order_notes')
    op.drop_index(op.f('ix_work_order_notes_visibility'), table_name='work_order_notes')
    op.drop_index(op.f('ix_work_order_notes_note_type'), table_name='work_order_notes')
    op.drop_index(op.f('ix_work_order_notes_is_pinned'), table_name='work_order_notes')
    op.drop_index(op.f('ix_work_order_notes_is_active'), table_name='work_order_notes')
    op.drop_index(op.f('ix_work_order_notes_author_user_id'), table_name='work_order_notes')
    op.drop_table('work_order_notes')
    # ### end Alembic commands ###
