"""create supplier payment and accounts payable foundation

Revision ID: ce9a5e9fc6dd
Revises: f05a4cdc40ff
Create Date: 2026-07-27 16:30:30.336081

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# Revision identifiers used by Alembic.
revision: str = 'ce9a5e9fc6dd'
down_revision: Union[str, Sequence[str], None] = 'f05a4cdc40ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_payments',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('payment_number', sa.String(length=50), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.String(length=30), server_default=sa.text("'bank_transfer'"), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'NGN'"), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('reference_number', sa.String(length=150), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'posted'"), nullable=False),
    sa.Column('recorded_by_user_id', sa.UUID(), nullable=True),
    sa.Column('reversed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('reversed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reversal_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("\n            (\n                status = 'posted'\n                AND reversed_at IS NULL\n                AND reversal_reason IS NULL\n            )\n            OR\n            (\n                status = 'reversed'\n                AND reversed_at IS NOT NULL\n                AND reversal_reason IS NOT NULL\n            )\n            ", name=op.f('ck_supplier_payments_reversal_state_valid')),
    sa.CheckConstraint("\n            payment_method IN (\n                'bank_transfer',\n                'cash',\n                'card',\n                'mobile_money',\n                'cheque',\n                'direct_debit',\n                'other'\n            )\n            ", name=op.f('ck_supplier_payments_method_valid')),
    sa.CheckConstraint("status IN ('posted', 'reversed')", name=op.f('ck_supplier_payments_status_valid')),
    sa.CheckConstraint('char_length(currency) = 3', name=op.f('ck_supplier_payments_currency_length_valid')),
    sa.CheckConstraint('total_amount > 0', name=op.f('ck_supplier_payments_total_amount_positive')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_supplier_payments_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], name=op.f('fk_supplier_payments_recorded_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reversed_by_user_id'], ['users.id'], name=op.f('fk_supplier_payments_reversed_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_supplier_payments_supplier_id_suppliers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_payments')),
    sa.UniqueConstraint('organization_id', 'payment_number', name='uq_supplier_payments_organization_number'),
    sa.UniqueConstraint('organization_id', 'supplier_id', 'reference_number', name='uq_supplier_payments_supplier_reference')
    )
    op.create_index(op.f('ix_supplier_payments_currency'), 'supplier_payments', ['currency'], unique=False)
    op.create_index('ix_supplier_payments_organization_date', 'supplier_payments', ['organization_id', 'payment_date'], unique=False)
    op.create_index(op.f('ix_supplier_payments_organization_id'), 'supplier_payments', ['organization_id'], unique=False)
    op.create_index('ix_supplier_payments_organization_status', 'supplier_payments', ['organization_id', 'status'], unique=False)
    op.create_index('ix_supplier_payments_organization_supplier', 'supplier_payments', ['organization_id', 'supplier_id'], unique=False)
    op.create_index(op.f('ix_supplier_payments_payment_date'), 'supplier_payments', ['payment_date'], unique=False)
    op.create_index(op.f('ix_supplier_payments_payment_method'), 'supplier_payments', ['payment_method'], unique=False)
    op.create_index(op.f('ix_supplier_payments_recorded_by_user_id'), 'supplier_payments', ['recorded_by_user_id'], unique=False)
    op.create_index(op.f('ix_supplier_payments_reference_number'), 'supplier_payments', ['reference_number'], unique=False)
    op.create_index(op.f('ix_supplier_payments_reversed_by_user_id'), 'supplier_payments', ['reversed_by_user_id'], unique=False)
    op.create_index(op.f('ix_supplier_payments_status'), 'supplier_payments', ['status'], unique=False)
    op.create_index('ix_supplier_payments_supplier_date', 'supplier_payments', ['supplier_id', 'payment_date'], unique=False)
    op.create_index(op.f('ix_supplier_payments_supplier_id'), 'supplier_payments', ['supplier_id'], unique=False)
    op.create_table('supplier_payment_allocations',
    sa.Column('supplier_payment_id', sa.UUID(), nullable=False),
    sa.Column('supplier_bill_id', sa.UUID(), nullable=False),
    sa.Column('amount_allocated', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount_allocated > 0', name=op.f('ck_supplier_payment_allocations_amount_positive')),
    sa.CheckConstraint('position >= 0', name=op.f('ck_supplier_payment_allocations_position_non_negative')),
    sa.ForeignKeyConstraint(['supplier_bill_id'], ['supplier_bills.id'], name=op.f('fk_supplier_payment_allocations_supplier_bill_id_supplier_bills'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_payment_id'], ['supplier_payments.id'], name=op.f('fk_supplier_payment_allocations_supplier_payment_id_supplier_payments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_payment_allocations')),
    sa.UniqueConstraint('supplier_payment_id', 'position', name='uq_supplier_payment_allocations_position'),
    sa.UniqueConstraint('supplier_payment_id', 'supplier_bill_id', name='uq_supplier_payment_allocations_bill')
    )
    op.create_index('ix_supplier_payment_allocations_bill_payment', 'supplier_payment_allocations', ['supplier_bill_id', 'supplier_payment_id'], unique=False)
    op.create_index(op.f('ix_supplier_payment_allocations_supplier_bill_id'), 'supplier_payment_allocations', ['supplier_bill_id'], unique=False)
    op.create_index(op.f('ix_supplier_payment_allocations_supplier_payment_id'), 'supplier_payment_allocations', ['supplier_payment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supplier_payment_allocations_supplier_payment_id'), table_name='supplier_payment_allocations')
    op.drop_index(op.f('ix_supplier_payment_allocations_supplier_bill_id'), table_name='supplier_payment_allocations')
    op.drop_index('ix_supplier_payment_allocations_bill_payment', table_name='supplier_payment_allocations')
    op.drop_table('supplier_payment_allocations')
    op.drop_index(op.f('ix_supplier_payments_supplier_id'), table_name='supplier_payments')
    op.drop_index('ix_supplier_payments_supplier_date', table_name='supplier_payments')
    op.drop_index(op.f('ix_supplier_payments_status'), table_name='supplier_payments')
    op.drop_index(op.f('ix_supplier_payments_reversed_by_user_id'), table_name='supplier_payments')
    op.drop_index(op.f('ix_supplier_payments_reference_number'), table_name='supplier_payments')
    op.drop_index(op.f('ix_supplier_payments_recorded_by_user_id'), table_name='supplier_payments')
    op.drop_index(op.f('ix_supplier_payments_payment_method'), table_name='supplier_payments')
    op.drop_index(op.f('ix_supplier_payments_payment_date'), table_name='supplier_payments')
    op.drop_index('ix_supplier_payments_organization_supplier', table_name='supplier_payments')
    op.drop_index('ix_supplier_payments_organization_status', table_name='supplier_payments')
    op.drop_index(op.f('ix_supplier_payments_organization_id'), table_name='supplier_payments')
    op.drop_index('ix_supplier_payments_organization_date', table_name='supplier_payments')
    op.drop_index(op.f('ix_supplier_payments_currency'), table_name='supplier_payments')
    op.drop_table('supplier_payments')
    # ### end Alembic commands ###
