"""create work order activity timeline

Revision ID: d66a91776c6a
Revises: eca8195f3bd6
Create Date: 2026-07-12 23:27:11.805723

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# Revision identifiers used by Alembic.
revision: str = 'd66a91776c6a'
down_revision: Union[str, Sequence[str], None] = 'eca8195f3bd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_order_activities',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('work_order_id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.String(length=255), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_work_order_activities_actor_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_work_order_activities_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], name=op.f('fk_work_order_activities_work_order_id_work_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_order_activities'))
    )
    op.create_index(op.f('ix_work_order_activities_activity_type'), 'work_order_activities', ['activity_type'], unique=False)
    op.create_index(op.f('ix_work_order_activities_actor_user_id'), 'work_order_activities', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_work_order_activities_organization_id'), 'work_order_activities', ['organization_id'], unique=False)
    op.create_index('ix_work_order_activities_organization_type', 'work_order_activities', ['organization_id', 'activity_type'], unique=False)
    op.create_index('ix_work_order_activities_organization_work_order', 'work_order_activities', ['organization_id', 'work_order_id'], unique=False)
    op.create_index('ix_work_order_activities_work_order_created', 'work_order_activities', ['work_order_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_work_order_activities_work_order_id'), 'work_order_activities', ['work_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_order_activities_work_order_id'), table_name='work_order_activities')
    op.drop_index('ix_work_order_activities_work_order_created', table_name='work_order_activities')
    op.drop_index('ix_work_order_activities_organization_work_order', table_name='work_order_activities')
    op.drop_index('ix_work_order_activities_organization_type', table_name='work_order_activities')
    op.drop_index(op.f('ix_work_order_activities_organization_id'), table_name='work_order_activities')
    op.drop_index(op.f('ix_work_order_activities_actor_user_id'), table_name='work_order_activities')
    op.drop_index(op.f('ix_work_order_activities_activity_type'), table_name='work_order_activities')
    op.drop_table('work_order_activities')
    # ### end Alembic commands ###
