"""Create inventory foundation.

Revision ID: d8ceb56a8f4f
Revises: d4f6a8c2e5b7
Create Date: 2026-07-20 16:19:07.813568
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = "d8ceb56a8f4f"
down_revision: str | Sequence[str] | None = "d4f6a8c2e5b7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """
    Create the inventory catalogue, storage, balance,
    reservation, and movement-ledger tables.
    """

    op.create_table(
        "inventory_items",
        sa.Column(
            "organization_id",
            sa.UUID(),
            nullable=False,
        ),
        sa.Column(
            "sku",
            sa.String(length=80),
            nullable=False,
        ),
        sa.Column(
            "barcode",
            sa.String(length=120),
            nullable=True,
        ),
        sa.Column(
            "name",
            sa.String(length=180),
            nullable=False,
        ),
        sa.Column(
            "item_type",
            sa.String(length=30),
            server_default=sa.text("'material'"),
            nullable=False,
        ),
        sa.Column(
            "category",
            sa.String(length=120),
            nullable=True,
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "unit_of_measure",
            sa.String(length=40),
            server_default=sa.text("'each'"),
            nullable=False,
        ),
        sa.Column(
            "default_unit_cost",
            sa.Numeric(
                precision=14,
                scale=4,
            ),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "currency",
            sa.String(length=3),
            server_default=sa.text("'NGN'"),
            nullable=False,
        ),
        sa.Column(
            "reorder_level",
            sa.Numeric(
                precision=16,
                scale=3,
            ),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "reorder_quantity",
            sa.Numeric(
                precision=16,
                scale=3,
            ),
            nullable=True,
        ),
        sa.Column(
            "preferred_supplier",
            sa.String(length=200),
            nullable=True,
        ),
        sa.Column(
            "details",
            postgresql.JSONB(
                astext_type=sa.Text(),
            ),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.UUID(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.CheckConstraint(
            """
            item_type IN (
                'material',
                'consumable',
                'spare_part',
                'supply',
                'fuel',
                'other'
            )
            """,
            name=op.f(
                "ck_inventory_items_type_valid"
            ),
        ),
        sa.CheckConstraint(
            "default_unit_cost >= 0",
            name=op.f(
                "ck_inventory_items_default_cost_non_negative"
            ),
        ),
        sa.CheckConstraint(
            "reorder_level >= 0",
            name=op.f(
                "ck_inventory_items_reorder_level_non_negative"
            ),
        ),
        sa.CheckConstraint(
            """
            reorder_quantity IS NULL
            OR reorder_quantity > 0
            """,
            name=op.f(
                "ck_inventory_items_reorder_quantity_positive"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f(
                "fk_inventory_items_organization_id_organizations"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f("pk_inventory_items"),
        ),
        sa.UniqueConstraint(
            "organization_id",
            "barcode",
            name="uq_inventory_items_organization_barcode",
        ),
        sa.UniqueConstraint(
            "organization_id",
            "sku",
            name="uq_inventory_items_organization_sku",
        ),
    )

    op.create_index(
        op.f("ix_inventory_items_category"),
        "inventory_items",
        ["category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_items_is_active"),
        "inventory_items",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_items_item_type"),
        "inventory_items",
        ["item_type"],
        unique=False,
    )
    op.create_index(
        "ix_inventory_items_organization_active",
        "inventory_items",
        ["organization_id", "is_active"],
        unique=False,
    )
    op.create_index(
        "ix_inventory_items_organization_category",
        "inventory_items",
        ["organization_id", "category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_items_organization_id"),
        "inventory_items",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_inventory_items_organization_name",
        "inventory_items",
        ["organization_id", "name"],
        unique=False,
    )
    op.create_index(
        "ix_inventory_items_organization_type",
        "inventory_items",
        ["organization_id", "item_type"],
        unique=False,
    )

    op.create_table(
        "inventory_locations",
        sa.Column(
            "organization_id",
            sa.UUID(),
            nullable=False,
        ),
        sa.Column(
            "code",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "name",
            sa.String(length=160),
            nullable=False,
        ),
        sa.Column(
            "location_type",
            sa.String(length=30),
            server_default=sa.text("'warehouse'"),
            nullable=False,
        ),
        sa.Column(
            "address",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "notes",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.UUID(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.CheckConstraint(
            """
            location_type IN (
                'warehouse',
                'store',
                'vehicle',
                'job_site',
                'technician',
                'other'
            )
            """,
            name=op.f(
                "ck_inventory_locations_type_valid"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f(
                "fk_inventory_locations_organization_id_organizations"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f("pk_inventory_locations"),
        ),
        sa.UniqueConstraint(
            "organization_id",
            "code",
            name="uq_inventory_locations_organization_code",
        ),
    )

    op.create_index(
        op.f("ix_inventory_locations_is_active"),
        "inventory_locations",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_locations_location_type"),
        "inventory_locations",
        ["location_type"],
        unique=False,
    )
    op.create_index(
        "ix_inventory_locations_organization_active",
        "inventory_locations",
        ["organization_id", "is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_locations_organization_id"),
        "inventory_locations",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_inventory_locations_organization_name",
        "inventory_locations",
        ["organization_id", "name"],
        unique=False,
    )
    op.create_index(
        "ix_inventory_locations_organization_type",
        "inventory_locations",
        ["organization_id", "location_type"],
        unique=False,
    )

    op.create_table(
        "inventory_balances",
        sa.Column(
            "organization_id",
            sa.UUID(),
            nullable=False,
        ),
        sa.Column(
            "item_id",
            sa.UUID(),
            nullable=False,
        ),
        sa.Column(
            "location_id",
            sa.UUID(),
            nullable=False,
        ),
        sa.Column(
            "quantity_on_hand",
            sa.Numeric(
                precision=16,
                scale=3,
            ),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "quantity_reserved",
            sa.Numeric(
                precision=16,
                scale=3,
            ),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "average_unit_cost",
            sa.Numeric(
                precision=14,
                scale=4,
            ),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "last_movement_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "id",
            sa.UUID(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.CheckConstraint(
            "quantity_on_hand >= 0",
            name=op.f(
                "ck_inventory_balances_on_hand_non_negative"
            ),
        ),
        sa.CheckConstraint(
            "quantity_reserved >= 0",
            name=op.f(
                "ck_inventory_balances_reserved_non_negative"
            ),
        ),
        sa.CheckConstraint(
            "quantity_reserved <= quantity_on_hand",
            name=op.f(
                "ck_inventory_balances_reserved_within_stock"
            ),
        ),
        sa.CheckConstraint(
            "average_unit_cost >= 0",
            name=op.f(
                "ck_inventory_balances_average_cost_non_negative"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["inventory_items.id"],
            name=op.f(
                "fk_inventory_balances_item_id_inventory_items"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["inventory_locations.id"],
            name=op.f(
                "fk_inventory_balances_location_id_inventory_locations"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f(
                "fk_inventory_balances_organization_id_organizations"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f("pk_inventory_balances"),
        ),
        sa.UniqueConstraint(
            "organization_id",
            "item_id",
            "location_id",
            name="uq_inventory_balances_item_location",
        ),
    )

    op.create_index(
        op.f("ix_inventory_balances_item_id"),
        "inventory_balances",
        ["item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_balances_last_movement_at"),
        "inventory_balances",
        ["last_movement_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_balances_location_id"),
        "inventory_balances",
        ["location_id"],
        unique=False,
    )
    op.create_index(
        "ix_inventory_balances_location_item",
        "inventory_balances",
        ["location_id", "item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_balances_organization_id"),
        "inventory_balances",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_inventory_balances_organization_item",
        "inventory_balances",
        ["organization_id", "item_id"],
        unique=False,
    )
    op.create_index(
        "ix_inventory_balances_organization_location",
        "inventory_balances",
        ["organization_id", "location_id"],
        unique=False,
    )

    op.create_table(
        "inventory_reservations",
        sa.Column(
            "organization_id",
            sa.UUID(),
            nullable=False,
        ),
        sa.Column(
            "item_id",
            sa.UUID(),
            nullable=False,
        ),
        sa.Column(
            "location_id",
            sa.UUID(),
            nullable=False,
        ),
        sa.Column(
            "work_order_id",
            sa.UUID(),
            nullable=False,
        ),
        sa.Column(
            "quantity_reserved",
            sa.Numeric(
                precision=16,
                scale=3,
            ),
            nullable=False,
        ),
        sa.Column(
            "quantity_consumed",
            sa.Numeric(
                precision=16,
                scale=3,
            ),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=30),
            server_default=sa.text("'active'"),
            nullable=False,
        ),
        sa.Column(
            "reserved_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "released_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "consumed_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "notes",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "created_by_user_id",
            sa.UUID(),
            nullable=True,
        ),
        sa.Column(
            "updated_by_user_id",
            sa.UUID(),
            nullable=True,
        ),
        sa.Column(
            "details",
            postgresql.JSONB(
                astext_type=sa.Text(),
            ),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.UUID(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.CheckConstraint(
            """
            status IN (
                'active',
                'partially_consumed',
                'consumed',
                'released',
                'cancelled'
            )
            """,
            name=op.f(
                "ck_inventory_reservations_status_valid"
            ),
        ),
        sa.CheckConstraint(
            "quantity_reserved > 0",
            name=op.f(
                "ck_inventory_reservations_quantity_positive"
            ),
        ),
        sa.CheckConstraint(
            "quantity_consumed >= 0",
            name=op.f(
                "ck_inventory_reservations_consumed_non_negative"
            ),
        ),
        sa.CheckConstraint(
            "quantity_consumed <= quantity_reserved",
            name=op.f(
                "ck_inventory_reservations_consumed_within_reserved"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f(
                "fk_inventory_reservations_created_by_user_id_users"
            ),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"],
            ["users.id"],
            name=op.f(
                "fk_inventory_reservations_updated_by_user_id_users"
            ),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["inventory_items.id"],
            name=op.f(
                "fk_inventory_reservations_item_id_inventory_items"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["inventory_locations.id"],
            name=op.f(
                "fk_inventory_reservations_location_id_inventory_locations"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f(
                "fk_inventory_reservations_organization_id_organizations"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["work_order_id"],
            ["work_orders.id"],
            name=op.f(
                "fk_inventory_reservations_work_order_id_work_orders"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f("pk_inventory_reservations"),
        ),
    )

    op.create_index(
        op.f(
            "ix_inventory_reservations_created_by_user_id"
        ),
        "inventory_reservations",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_reservations_expires_at"),
        "inventory_reservations",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_reservations_is_active"),
        "inventory_reservations",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_reservations_item_id"),
        "inventory_reservations",
        ["item_id"],
        unique=False,
    )
    op.create_index(
        "ix_inventory_reservations_item_location",
        "inventory_reservations",
        ["item_id", "location_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_reservations_location_id"),
        "inventory_reservations",
        ["location_id"],
        unique=False,
    )
    op.create_index(
        "ix_inventory_reservations_organization_created",
        "inventory_reservations",
        ["organization_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_reservations_organization_id"),
        "inventory_reservations",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_inventory_reservations_organization_status",
        "inventory_reservations",
        ["organization_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_reservations_status"),
        "inventory_reservations",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f(
            "ix_inventory_reservations_updated_by_user_id"
        ),
        "inventory_reservations",
        ["updated_by_user_id"],
        unique=False,
    )
    op.create_index(
        "ix_inventory_reservations_work_order",
        "inventory_reservations",
        ["work_order_id"],
        unique=False,
    )

    op.create_table(
        "inventory_movements",
        sa.Column(
            "organization_id",
            sa.UUID(),
            nullable=False,
        ),
        sa.Column(
            "item_id",
            sa.UUID(),
            nullable=False,
        ),
        sa.Column(
            "location_id",
            sa.UUID(),
            nullable=False,
        ),
        sa.Column(
            "work_order_id",
            sa.UUID(),
            nullable=True,
        ),
        sa.Column(
            "reservation_id",
            sa.UUID(),
            nullable=True,
        ),
        sa.Column(
            "movement_type",
            sa.String(length=30),
            nullable=False,
        ),
        sa.Column(
            "quantity",
            sa.Numeric(
                precision=16,
                scale=3,
            ),
            nullable=False,
        ),
        sa.Column(
            "quantity_delta",
            sa.Numeric(
                precision=16,
                scale=3,
            ),
            nullable=False,
        ),
        sa.Column(
            "quantity_before",
            sa.Numeric(
                precision=16,
                scale=3,
            ),
            nullable=False,
        ),
        sa.Column(
            "quantity_after",
            sa.Numeric(
                precision=16,
                scale=3,
            ),
            nullable=False,
        ),
        sa.Column(
            "unit_cost",
            sa.Numeric(
                precision=14,
                scale=4,
            ),
            nullable=True,
        ),
        sa.Column(
            "currency",
            sa.String(length=3),
            server_default=sa.text("'NGN'"),
            nullable=False,
        ),
        sa.Column(
            "reference_type",
            sa.String(length=50),
            nullable=True,
        ),
        sa.Column(
            "reference_id",
            sa.String(length=120),
            nullable=True,
        ),
        sa.Column(
            "transfer_group_id",
            sa.UUID(),
            nullable=True,
        ),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "notes",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "created_by_user_id",
            sa.UUID(),
            nullable=True,
        ),
        sa.Column(
            "details",
            postgresql.JSONB(
                astext_type=sa.Text(),
            ),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.UUID(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.CheckConstraint(
            """
            movement_type IN (
                'opening_balance',
                'receipt',
                'issue',
                'return',
                'adjustment_in',
                'adjustment_out',
                'transfer_in',
                'transfer_out'
            )
            """,
            name=op.f(
                "ck_inventory_movements_type_valid"
            ),
        ),
        sa.CheckConstraint(
            "quantity > 0",
            name=op.f(
                "ck_inventory_movements_quantity_positive"
            ),
        ),
        sa.CheckConstraint(
            "quantity_delta <> 0",
            name=op.f(
                "ck_inventory_movements_delta_non_zero"
            ),
        ),
        sa.CheckConstraint(
            "quantity_before >= 0",
            name=op.f(
                "ck_inventory_movements_before_non_negative"
            ),
        ),
        sa.CheckConstraint(
            "quantity_after >= 0",
            name=op.f(
                "ck_inventory_movements_after_non_negative"
            ),
        ),
        sa.CheckConstraint(
            """
            quantity_after
            = quantity_before + quantity_delta
            """,
            name=op.f(
                "ck_inventory_movements_balance_consistent"
            ),
        ),
        sa.CheckConstraint(
            """
            unit_cost IS NULL
            OR unit_cost >= 0
            """,
            name=op.f(
                "ck_inventory_movements_unit_cost_non_negative"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f(
                "fk_inventory_movements_created_by_user_id_users"
            ),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["inventory_items.id"],
            name=op.f(
                "fk_inventory_movements_item_id_inventory_items"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["inventory_locations.id"],
            name=op.f(
                "fk_inventory_movements_location_id_inventory_locations"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f(
                "fk_inventory_movements_organization_id_organizations"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["inventory_reservations.id"],
            name=op.f(
                "fk_inventory_movements_reservation_id_inventory_reservations"
            ),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["work_order_id"],
            ["work_orders.id"],
            name=op.f(
                "fk_inventory_movements_work_order_id_work_orders"
            ),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f("pk_inventory_movements"),
        ),
    )

    op.create_index(
        op.f("ix_inventory_movements_created_by_user_id"),
        "inventory_movements",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_movements_item_id"),
        "inventory_movements",
        ["item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_movements_location_id"),
        "inventory_movements",
        ["location_id"],
        unique=False,
    )
    op.create_index(
        "ix_inventory_movements_location_time",
        "inventory_movements",
        ["location_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_movements_movement_type"),
        "inventory_movements",
        ["movement_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_movements_occurred_at"),
        "inventory_movements",
        ["occurred_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_movements_organization_id"),
        "inventory_movements",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_inventory_movements_organization_item_time",
        "inventory_movements",
        ["organization_id", "item_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_inventory_movements_reference",
        "inventory_movements",
        ["reference_type", "reference_id"],
        unique=False,
    )
    op.create_index(
        "ix_inventory_movements_reservation",
        "inventory_movements",
        ["reservation_id"],
        unique=False,
    )
    op.create_index(
        "ix_inventory_movements_transfer_group",
        "inventory_movements",
        ["transfer_group_id"],
        unique=False,
    )
    op.create_index(
        "ix_inventory_movements_work_order",
        "inventory_movements",
        ["work_order_id"],
        unique=False,
    )


def downgrade() -> None:
    """
    Remove the inventory foundation in dependency-safe order.
    """

    op.drop_table("inventory_movements")
    op.drop_table("inventory_reservations")
    op.drop_table("inventory_balances")
    op.drop_table("inventory_locations")
    op.drop_table("inventory_items")