"""create purchase requisition foundation

Revision ID: eabe9eac121c
Revises: b09ec732449f
Create Date: 2026-07-27 13:35:48.698005

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# Revision identifiers used by Alembic.
revision: str = 'eabe9eac121c'
down_revision: Union[str, Sequence[str], None] = 'b09ec732449f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_requisitions',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('requisition_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('priority', sa.String(length=20), server_default=sa.text("'normal'"), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'NGN'"), nullable=False),
    sa.Column('preferred_supplier_id', sa.UUID(), nullable=True),
    sa.Column('work_order_id', sa.UUID(), nullable=True),
    sa.Column('delivery_location_id', sa.UUID(), nullable=True),
    sa.Column('requested_delivery_date', sa.Date(), nullable=True),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('total_estimated_amount', sa.Numeric(precision=16, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('submitted_by_user_id', sa.UUID(), nullable=True),
    sa.Column('approved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('rejected_by_user_id', sa.UUID(), nullable=True),
    sa.Column('cancelled_by_user_id', sa.UUID(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("\n            status IN (\n                'draft',\n                'submitted',\n                'approved',\n                'rejected',\n                'cancelled',\n                'converted'\n            )\n            ", name=op.f('ck_purchase_requisitions_status_valid')),
    sa.CheckConstraint("priority IN ('low', 'normal', 'high', 'urgent')", name=op.f('ck_purchase_requisitions_priority_valid')),
    sa.CheckConstraint('char_length(currency) = 3', name=op.f('ck_purchase_requisitions_currency_length_valid')),
    sa.CheckConstraint('total_estimated_amount >= 0', name=op.f('ck_purchase_requisitions_total_non_negative')),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], name=op.f('fk_purchase_requisitions_approved_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cancelled_by_user_id'], ['users.id'], name=op.f('fk_purchase_requisitions_cancelled_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_purchase_requisitions_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['delivery_location_id'], ['inventory_locations.id'], name=op.f('fk_purchase_requisitions_delivery_location_id_inventory_locations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_purchase_requisitions_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['preferred_supplier_id'], ['suppliers.id'], name=op.f('fk_purchase_requisitions_preferred_supplier_id_suppliers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rejected_by_user_id'], ['users.id'], name=op.f('fk_purchase_requisitions_rejected_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], name=op.f('fk_purchase_requisitions_submitted_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], name=op.f('fk_purchase_requisitions_work_order_id_work_orders'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_requisitions')),
    sa.UniqueConstraint('organization_id', 'requisition_number', name='uq_purchase_requisitions_organization_number')
    )
    op.create_index(op.f('ix_purchase_requisitions_approved_by_user_id'), 'purchase_requisitions', ['approved_by_user_id'], unique=False)
    op.create_index(op.f('ix_purchase_requisitions_cancelled_by_user_id'), 'purchase_requisitions', ['cancelled_by_user_id'], unique=False)
    op.create_index(op.f('ix_purchase_requisitions_created_by_user_id'), 'purchase_requisitions', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_purchase_requisitions_currency'), 'purchase_requisitions', ['currency'], unique=False)
    op.create_index(op.f('ix_purchase_requisitions_delivery_location_id'), 'purchase_requisitions', ['delivery_location_id'], unique=False)
    op.create_index(op.f('ix_purchase_requisitions_is_active'), 'purchase_requisitions', ['is_active'], unique=False)
    op.create_index('ix_purchase_requisitions_organization_active', 'purchase_requisitions', ['organization_id', 'is_active'], unique=False)
    op.create_index('ix_purchase_requisitions_organization_delivery', 'purchase_requisitions', ['organization_id', 'requested_delivery_date'], unique=False)
    op.create_index(op.f('ix_purchase_requisitions_organization_id'), 'purchase_requisitions', ['organization_id'], unique=False)
    op.create_index('ix_purchase_requisitions_organization_priority', 'purchase_requisitions', ['organization_id', 'priority'], unique=False)
    op.create_index('ix_purchase_requisitions_organization_status', 'purchase_requisitions', ['organization_id', 'status'], unique=False)
    op.create_index('ix_purchase_requisitions_organization_supplier', 'purchase_requisitions', ['organization_id', 'preferred_supplier_id'], unique=False)
    op.create_index('ix_purchase_requisitions_organization_work_order', 'purchase_requisitions', ['organization_id', 'work_order_id'], unique=False)
    op.create_index(op.f('ix_purchase_requisitions_preferred_supplier_id'), 'purchase_requisitions', ['preferred_supplier_id'], unique=False)
    op.create_index(op.f('ix_purchase_requisitions_priority'), 'purchase_requisitions', ['priority'], unique=False)
    op.create_index(op.f('ix_purchase_requisitions_rejected_by_user_id'), 'purchase_requisitions', ['rejected_by_user_id'], unique=False)
    op.create_index(op.f('ix_purchase_requisitions_requested_delivery_date'), 'purchase_requisitions', ['requested_delivery_date'], unique=False)
    op.create_index(op.f('ix_purchase_requisitions_status'), 'purchase_requisitions', ['status'], unique=False)
    op.create_index(op.f('ix_purchase_requisitions_submitted_by_user_id'), 'purchase_requisitions', ['submitted_by_user_id'], unique=False)
    op.create_index(op.f('ix_purchase_requisitions_work_order_id'), 'purchase_requisitions', ['work_order_id'], unique=False)
    op.create_table('purchase_requisition_line_items',
    sa.Column('requisition_id', sa.UUID(), nullable=False),
    sa.Column('inventory_item_id', sa.UUID(), nullable=True),
    sa.Column('preferred_supplier_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=16, scale=3), server_default=sa.text('1.000'), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=40), server_default=sa.text("'each'"), nullable=False),
    sa.Column('estimated_unit_cost', sa.Numeric(precision=14, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=16, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('estimated_unit_cost >= 0', name=op.f('ck_purchase_requisition_line_items_unit_cost_non_negative')),
    sa.CheckConstraint('line_total >= 0', name=op.f('ck_purchase_requisition_line_items_line_total_non_negative')),
    sa.CheckConstraint('position >= 0', name=op.f('ck_purchase_requisition_line_items_position_non_negative')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_purchase_requisition_line_items_quantity_positive')),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], name=op.f('fk_purchase_requisition_line_items_inventory_item_id_inventory_items'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['preferred_supplier_id'], ['suppliers.id'], name=op.f('fk_purchase_requisition_line_items_preferred_supplier_id_suppliers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requisition_id'], ['purchase_requisitions.id'], name=op.f('fk_purchase_requisition_line_items_requisition_id_purchase_requisitions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_requisition_line_items')),
    sa.UniqueConstraint('requisition_id', 'position', name='uq_purchase_requisition_lines_position')
    )
    op.create_index(op.f('ix_purchase_requisition_line_items_inventory_item_id'), 'purchase_requisition_line_items', ['inventory_item_id'], unique=False)
    op.create_index(op.f('ix_purchase_requisition_line_items_preferred_supplier_id'), 'purchase_requisition_line_items', ['preferred_supplier_id'], unique=False)
    op.create_index(op.f('ix_purchase_requisition_line_items_requisition_id'), 'purchase_requisition_line_items', ['requisition_id'], unique=False)
    op.create_index('ix_purchase_requisition_lines_requisition_item', 'purchase_requisition_line_items', ['requisition_id', 'inventory_item_id'], unique=False)
    op.create_index('ix_purchase_requisition_lines_requisition_supplier', 'purchase_requisition_line_items', ['requisition_id', 'preferred_supplier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_purchase_requisition_lines_requisition_supplier', table_name='purchase_requisition_line_items')
    op.drop_index('ix_purchase_requisition_lines_requisition_item', table_name='purchase_requisition_line_items')
    op.drop_index(op.f('ix_purchase_requisition_line_items_requisition_id'), table_name='purchase_requisition_line_items')
    op.drop_index(op.f('ix_purchase_requisition_line_items_preferred_supplier_id'), table_name='purchase_requisition_line_items')
    op.drop_index(op.f('ix_purchase_requisition_line_items_inventory_item_id'), table_name='purchase_requisition_line_items')
    op.drop_table('purchase_requisition_line_items')
    op.drop_index(op.f('ix_purchase_requisitions_work_order_id'), table_name='purchase_requisitions')
    op.drop_index(op.f('ix_purchase_requisitions_submitted_by_user_id'), table_name='purchase_requisitions')
    op.drop_index(op.f('ix_purchase_requisitions_status'), table_name='purchase_requisitions')
    op.drop_index(op.f('ix_purchase_requisitions_requested_delivery_date'), table_name='purchase_requisitions')
    op.drop_index(op.f('ix_purchase_requisitions_rejected_by_user_id'), table_name='purchase_requisitions')
    op.drop_index(op.f('ix_purchase_requisitions_priority'), table_name='purchase_requisitions')
    op.drop_index(op.f('ix_purchase_requisitions_preferred_supplier_id'), table_name='purchase_requisitions')
    op.drop_index('ix_purchase_requisitions_organization_work_order', table_name='purchase_requisitions')
    op.drop_index('ix_purchase_requisitions_organization_supplier', table_name='purchase_requisitions')
    op.drop_index('ix_purchase_requisitions_organization_status', table_name='purchase_requisitions')
    op.drop_index('ix_purchase_requisitions_organization_priority', table_name='purchase_requisitions')
    op.drop_index(op.f('ix_purchase_requisitions_organization_id'), table_name='purchase_requisitions')
    op.drop_index('ix_purchase_requisitions_organization_delivery', table_name='purchase_requisitions')
    op.drop_index('ix_purchase_requisitions_organization_active', table_name='purchase_requisitions')
    op.drop_index(op.f('ix_purchase_requisitions_is_active'), table_name='purchase_requisitions')
    op.drop_index(op.f('ix_purchase_requisitions_delivery_location_id'), table_name='purchase_requisitions')
    op.drop_index(op.f('ix_purchase_requisitions_currency'), table_name='purchase_requisitions')
    op.drop_index(op.f('ix_purchase_requisitions_created_by_user_id'), table_name='purchase_requisitions')
    op.drop_index(op.f('ix_purchase_requisitions_cancelled_by_user_id'), table_name='purchase_requisitions')
    op.drop_index(op.f('ix_purchase_requisitions_approved_by_user_id'), table_name='purchase_requisitions')
    op.drop_table('purchase_requisitions')
    # ### end Alembic commands ###
