"""create work order checklist items

Revision ID: ebb5dd8c761e
Revises: d66a91776c6a
Create Date: 2026-07-13 22:47:51.612870

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# Revision identifiers used by Alembic.
revision: str = 'ebb5dd8c761e'
down_revision: Union[str, Sequence[str], None] = 'd66a91776c6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_order_checklist_items',
    sa.Column('work_order_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='pending', nullable=False),
    sa.Column('is_required', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('completion_note', sa.Text(), nullable=True),
    sa.Column('completed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('skipped_by_user_id', sa.UUID(), nullable=True),
    sa.Column('skipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'completed', 'skipped')", name=op.f('ck_work_order_checklist_items_ck_work_order_checklist_status_valid')),
    sa.CheckConstraint('position >= 0', name=op.f('ck_work_order_checklist_items_ck_work_order_checklist_position_non_negative')),
    sa.ForeignKeyConstraint(['completed_by_user_id'], ['users.id'], name=op.f('fk_work_order_checklist_items_completed_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['skipped_by_user_id'], ['users.id'], name=op.f('fk_work_order_checklist_items_skipped_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], name=op.f('fk_work_order_checklist_items_work_order_id_work_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_order_checklist_items')),
    sa.UniqueConstraint('work_order_id', 'position', name='uq_work_order_checklist_position')
    )
    op.create_index(op.f('ix_work_order_checklist_items_completed_by_user_id'), 'work_order_checklist_items', ['completed_by_user_id'], unique=False)
    op.create_index(op.f('ix_work_order_checklist_items_is_active'), 'work_order_checklist_items', ['is_active'], unique=False)
    op.create_index(op.f('ix_work_order_checklist_items_skipped_by_user_id'), 'work_order_checklist_items', ['skipped_by_user_id'], unique=False)
    op.create_index(op.f('ix_work_order_checklist_items_status'), 'work_order_checklist_items', ['status'], unique=False)
    op.create_index(op.f('ix_work_order_checklist_items_work_order_id'), 'work_order_checklist_items', ['work_order_id'], unique=False)
    op.create_index('ix_work_order_checklist_work_order_active_position', 'work_order_checklist_items', ['work_order_id', 'is_active', 'position'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_work_order_checklist_work_order_active_position', table_name='work_order_checklist_items')
    op.drop_index(op.f('ix_work_order_checklist_items_work_order_id'), table_name='work_order_checklist_items')
    op.drop_index(op.f('ix_work_order_checklist_items_status'), table_name='work_order_checklist_items')
    op.drop_index(op.f('ix_work_order_checklist_items_skipped_by_user_id'), table_name='work_order_checklist_items')
    op.drop_index(op.f('ix_work_order_checklist_items_is_active'), table_name='work_order_checklist_items')
    op.drop_index(op.f('ix_work_order_checklist_items_completed_by_user_id'), table_name='work_order_checklist_items')
    op.drop_table('work_order_checklist_items')
    # ### end Alembic commands ###
