"""create work orders and assignments

Revision ID: eca8195f3bd6
Revises: 435be83e2634
Create Date: 2026-07-12 19:32:38.355234

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# Revision identifiers used by Alembic.
revision: str = 'eca8195f3bd6'
down_revision: Union[str, Sequence[str], None] = '435be83e2634'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_orders',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('customer_site_id', sa.UUID(), nullable=True),
    sa.Column('work_order_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('job_type', sa.String(length=100), nullable=True),
    sa.Column('customer_reference', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('actual_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('completion_notes', sa.Text(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_work_orders_customer_id_customers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_site_id'], ['customer_sites.id'], name=op.f('fk_work_orders_customer_site_id_customer_sites'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_work_orders_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_orders')),
    sa.UniqueConstraint('organization_id', 'work_order_number', name='uq_work_orders_organization_number')
    )
    op.create_index(op.f('ix_work_orders_customer_id'), 'work_orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_work_orders_customer_site_id'), 'work_orders', ['customer_site_id'], unique=False)
    op.create_index(op.f('ix_work_orders_is_active'), 'work_orders', ['is_active'], unique=False)
    op.create_index('ix_work_orders_organization_active', 'work_orders', ['organization_id', 'is_active'], unique=False)
    op.create_index('ix_work_orders_organization_customer', 'work_orders', ['organization_id', 'customer_id'], unique=False)
    op.create_index(op.f('ix_work_orders_organization_id'), 'work_orders', ['organization_id'], unique=False)
    op.create_index('ix_work_orders_organization_priority', 'work_orders', ['organization_id', 'priority'], unique=False)
    op.create_index('ix_work_orders_organization_site', 'work_orders', ['organization_id', 'customer_site_id'], unique=False)
    op.create_index('ix_work_orders_organization_status', 'work_orders', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_work_orders_priority'), 'work_orders', ['priority'], unique=False)
    op.create_index('ix_work_orders_scheduled_start', 'work_orders', ['scheduled_start'], unique=False)
    op.create_index(op.f('ix_work_orders_status'), 'work_orders', ['status'], unique=False)
    op.create_table('work_order_asset_assignments',
    sa.Column('work_order_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_work_order_asset_assignments_asset_id_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], name=op.f('fk_work_order_asset_assignments_work_order_id_work_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_order_asset_assignments')),
    sa.UniqueConstraint('work_order_id', 'asset_id', name='uq_work_order_asset_assignment')
    )
    op.create_index('ix_work_order_asset_asset', 'work_order_asset_assignments', ['asset_id'], unique=False)
    op.create_index('ix_work_order_asset_work_order', 'work_order_asset_assignments', ['work_order_id'], unique=False)
    op.create_table('work_order_workforce_assignments',
    sa.Column('work_order_id', sa.UUID(), nullable=False),
    sa.Column('workforce_profile_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], name=op.f('fk_work_order_workforce_assignments_work_order_id_work_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workforce_profile_id'], ['workforce_profiles.id'], name=op.f('fk_work_order_workforce_assignments_workforce_profile_id_workforce_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_order_workforce_assignments')),
    sa.UniqueConstraint('work_order_id', 'workforce_profile_id', name='uq_work_order_workforce_assignment')
    )
    op.create_index('ix_work_order_workforce_profile', 'work_order_workforce_assignments', ['workforce_profile_id'], unique=False)
    op.create_index('ix_work_order_workforce_work_order', 'work_order_workforce_assignments', ['work_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_work_order_workforce_work_order', table_name='work_order_workforce_assignments')
    op.drop_index('ix_work_order_workforce_profile', table_name='work_order_workforce_assignments')
    op.drop_table('work_order_workforce_assignments')
    op.drop_index('ix_work_order_asset_work_order', table_name='work_order_asset_assignments')
    op.drop_index('ix_work_order_asset_asset', table_name='work_order_asset_assignments')
    op.drop_table('work_order_asset_assignments')
    op.drop_index(op.f('ix_work_orders_status'), table_name='work_orders')
    op.drop_index('ix_work_orders_scheduled_start', table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_priority'), table_name='work_orders')
    op.drop_index('ix_work_orders_organization_status', table_name='work_orders')
    op.drop_index('ix_work_orders_organization_site', table_name='work_orders')
    op.drop_index('ix_work_orders_organization_priority', table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_organization_id'), table_name='work_orders')
    op.drop_index('ix_work_orders_organization_customer', table_name='work_orders')
    op.drop_index('ix_work_orders_organization_active', table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_is_active'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_customer_site_id'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_customer_id'), table_name='work_orders')
    op.drop_table('work_orders')
    # ### end Alembic commands ###
