"""create supplier bill and three way matching foundation

Revision ID: f05a4cdc40ff
Revises: b1859e807f6e
Create Date: 2026-07-27 16:01:57.512121

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# Revision identifiers used by Alembic.
revision: str = 'f05a4cdc40ff'
down_revision: Union[str, Sequence[str], None] = 'b1859e807f6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_bills',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('supplier_bill_number', sa.String(length=50), nullable=False),
    sa.Column('supplier_invoice_number', sa.String(length=120), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_id', sa.UUID(), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('match_status', sa.String(length=30), server_default=sa.text("'not_run'"), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'NGN'"), nullable=False),
    sa.Column('quantity_tolerance_percent', sa.Numeric(precision=7, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('price_tolerance_percent', sa.Numeric(precision=7, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=16, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=16, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=16, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('submitted_by_user_id', sa.UUID(), nullable=True),
    sa.Column('matched_by_user_id', sa.UUID(), nullable=True),
    sa.Column('approved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('voided_by_user_id', sa.UUID(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('matched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approval_override_reason', sa.Text(), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("\n            status IN (\n                'draft',\n                'submitted',\n                'matched',\n                'exception',\n                'approved',\n                'voided'\n            )\n            ", name=op.f('ck_supplier_bills_status_valid')),
    sa.CheckConstraint("match_status IN ('not_run', 'matched', 'exception')", name=op.f('ck_supplier_bills_match_status_valid')),
    sa.CheckConstraint('char_length(currency) = 3', name=op.f('ck_supplier_bills_currency_length_valid')),
    sa.CheckConstraint('price_tolerance_percent >= 0 AND price_tolerance_percent <= 100', name=op.f('ck_supplier_bills_price_tolerance_valid')),
    sa.CheckConstraint('quantity_tolerance_percent >= 0 AND quantity_tolerance_percent <= 100', name=op.f('ck_supplier_bills_quantity_tolerance_valid')),
    sa.CheckConstraint('subtotal >= 0', name=op.f('ck_supplier_bills_subtotal_non_negative')),
    sa.CheckConstraint('tax_total >= 0', name=op.f('ck_supplier_bills_tax_total_non_negative')),
    sa.CheckConstraint('total_amount >= 0', name=op.f('ck_supplier_bills_total_amount_non_negative')),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], name=op.f('fk_supplier_bills_approved_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_supplier_bills_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matched_by_user_id'], ['users.id'], name=op.f('fk_supplier_bills_matched_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_supplier_bills_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], name=op.f('fk_supplier_bills_purchase_order_id_purchase_orders'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], name=op.f('fk_supplier_bills_submitted_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_supplier_bills_supplier_id_suppliers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['voided_by_user_id'], ['users.id'], name=op.f('fk_supplier_bills_voided_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_bills')),
    sa.UniqueConstraint('organization_id', 'supplier_bill_number', name='uq_supplier_bills_organization_number'),
    sa.UniqueConstraint('organization_id', 'supplier_id', 'supplier_invoice_number', name='uq_supplier_bills_supplier_invoice')
    )
    op.create_index(op.f('ix_supplier_bills_approved_by_user_id'), 'supplier_bills', ['approved_by_user_id'], unique=False)
    op.create_index(op.f('ix_supplier_bills_created_by_user_id'), 'supplier_bills', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_supplier_bills_currency'), 'supplier_bills', ['currency'], unique=False)
    op.create_index(op.f('ix_supplier_bills_due_date'), 'supplier_bills', ['due_date'], unique=False)
    op.create_index(op.f('ix_supplier_bills_invoice_date'), 'supplier_bills', ['invoice_date'], unique=False)
    op.create_index(op.f('ix_supplier_bills_is_active'), 'supplier_bills', ['is_active'], unique=False)
    op.create_index(op.f('ix_supplier_bills_match_status'), 'supplier_bills', ['match_status'], unique=False)
    op.create_index(op.f('ix_supplier_bills_matched_by_user_id'), 'supplier_bills', ['matched_by_user_id'], unique=False)
    op.create_index('ix_supplier_bills_organization_active', 'supplier_bills', ['organization_id', 'is_active'], unique=False)
    op.create_index('ix_supplier_bills_organization_due_date', 'supplier_bills', ['organization_id', 'due_date'], unique=False)
    op.create_index(op.f('ix_supplier_bills_organization_id'), 'supplier_bills', ['organization_id'], unique=False)
    op.create_index('ix_supplier_bills_organization_invoice_date', 'supplier_bills', ['organization_id', 'invoice_date'], unique=False)
    op.create_index('ix_supplier_bills_organization_match_status', 'supplier_bills', ['organization_id', 'match_status'], unique=False)
    op.create_index('ix_supplier_bills_organization_purchase_order', 'supplier_bills', ['organization_id', 'purchase_order_id'], unique=False)
    op.create_index('ix_supplier_bills_organization_status', 'supplier_bills', ['organization_id', 'status'], unique=False)
    op.create_index('ix_supplier_bills_organization_supplier', 'supplier_bills', ['organization_id', 'supplier_id'], unique=False)
    op.create_index(op.f('ix_supplier_bills_purchase_order_id'), 'supplier_bills', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_supplier_bills_status'), 'supplier_bills', ['status'], unique=False)
    op.create_index(op.f('ix_supplier_bills_submitted_by_user_id'), 'supplier_bills', ['submitted_by_user_id'], unique=False)
    op.create_index(op.f('ix_supplier_bills_supplier_id'), 'supplier_bills', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_supplier_bills_supplier_invoice_number'), 'supplier_bills', ['supplier_invoice_number'], unique=False)
    op.create_index(op.f('ix_supplier_bills_voided_by_user_id'), 'supplier_bills', ['voided_by_user_id'], unique=False)
    op.create_table('supplier_bill_line_items',
    sa.Column('supplier_bill_id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_line_item_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity_billed', sa.Numeric(precision=16, scale=3), server_default=sa.text('1.000'), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=40), server_default=sa.text("'each'"), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=7, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('line_subtotal', sa.Numeric(precision=16, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=16, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=16, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('line_subtotal >= 0', name=op.f('ck_supplier_bill_line_items_line_subtotal_non_negative')),
    sa.CheckConstraint('line_total >= 0', name=op.f('ck_supplier_bill_line_items_line_total_non_negative')),
    sa.CheckConstraint('position >= 0', name=op.f('ck_supplier_bill_line_items_position_non_negative')),
    sa.CheckConstraint('quantity_billed > 0', name=op.f('ck_supplier_bill_line_items_quantity_billed_positive')),
    sa.CheckConstraint('tax_amount >= 0', name=op.f('ck_supplier_bill_line_items_tax_amount_non_negative')),
    sa.CheckConstraint('tax_rate >= 0 AND tax_rate <= 100', name=op.f('ck_supplier_bill_line_items_tax_rate_valid')),
    sa.CheckConstraint('unit_price >= 0', name=op.f('ck_supplier_bill_line_items_unit_price_non_negative')),
    sa.ForeignKeyConstraint(['purchase_order_line_item_id'], ['purchase_order_line_items.id'], name=op.f('fk_supplier_bill_line_items_purchase_order_line_item_id_purchase_order_line_items'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_bill_id'], ['supplier_bills.id'], name=op.f('fk_supplier_bill_line_items_supplier_bill_id_supplier_bills'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_bill_line_items')),
    sa.UniqueConstraint('supplier_bill_id', 'position', name='uq_supplier_bill_lines_position'),
    sa.UniqueConstraint('supplier_bill_id', 'purchase_order_line_item_id', name='uq_supplier_bill_lines_purchase_order_line')
    )
    op.create_index(op.f('ix_supplier_bill_line_items_purchase_order_line_item_id'), 'supplier_bill_line_items', ['purchase_order_line_item_id'], unique=False)
    op.create_index(op.f('ix_supplier_bill_line_items_supplier_bill_id'), 'supplier_bill_line_items', ['supplier_bill_id'], unique=False)
    op.create_index('ix_supplier_bill_lines_bill_order_line', 'supplier_bill_line_items', ['supplier_bill_id', 'purchase_order_line_item_id'], unique=False)
    op.create_table('supplier_bill_match_results',
    sa.Column('supplier_bill_id', sa.UUID(), nullable=False),
    sa.Column('supplier_bill_line_item_id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_line_item_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('quantity_ordered', sa.Numeric(precision=16, scale=3), nullable=False),
    sa.Column('quantity_received', sa.Numeric(precision=16, scale=3), nullable=False),
    sa.Column('quantity_billed', sa.Numeric(precision=16, scale=3), nullable=False),
    sa.Column('purchase_order_unit_price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('supplier_bill_unit_price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('quantity_variance', sa.Numeric(precision=16, scale=3), nullable=False),
    sa.Column('unit_price_variance', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('quantity_variance_percent', sa.Numeric(precision=9, scale=4), nullable=False),
    sa.Column('unit_price_variance_percent', sa.Numeric(precision=9, scale=4), nullable=False),
    sa.Column('quantity_within_tolerance', sa.Boolean(), nullable=False),
    sa.Column('price_within_tolerance', sa.Boolean(), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('evaluated_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('matched', 'exception')", name=op.f('ck_supplier_bill_match_results_status_valid')),
    sa.CheckConstraint('purchase_order_unit_price >= 0', name=op.f('ck_supplier_bill_match_results_purchase_order_unit_price_non_negative')),
    sa.CheckConstraint('quantity_billed > 0', name=op.f('ck_supplier_bill_match_results_quantity_billed_positive')),
    sa.CheckConstraint('quantity_ordered >= 0', name=op.f('ck_supplier_bill_match_results_quantity_ordered_non_negative')),
    sa.CheckConstraint('quantity_received >= 0', name=op.f('ck_supplier_bill_match_results_quantity_received_non_negative')),
    sa.CheckConstraint('supplier_bill_unit_price >= 0', name=op.f('ck_supplier_bill_match_results_supplier_bill_unit_price_non_negative')),
    sa.ForeignKeyConstraint(['evaluated_by_user_id'], ['users.id'], name=op.f('fk_supplier_bill_match_results_evaluated_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['purchase_order_line_item_id'], ['purchase_order_line_items.id'], name=op.f('fk_supplier_bill_match_results_purchase_order_line_item_id_purchase_order_line_items'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_bill_id'], ['supplier_bills.id'], name=op.f('fk_supplier_bill_match_results_supplier_bill_id_supplier_bills'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_bill_line_item_id'], ['supplier_bill_line_items.id'], name=op.f('fk_supplier_bill_match_results_supplier_bill_line_item_id_supplier_bill_line_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_bill_match_results')),
    sa.UniqueConstraint('supplier_bill_line_item_id', name='uq_supplier_bill_match_results_line')
    )
    op.create_index('ix_supplier_bill_match_results_bill_status', 'supplier_bill_match_results', ['supplier_bill_id', 'status'], unique=False)
    op.create_index(op.f('ix_supplier_bill_match_results_evaluated_by_user_id'), 'supplier_bill_match_results', ['evaluated_by_user_id'], unique=False)
    op.create_index(op.f('ix_supplier_bill_match_results_purchase_order_line_item_id'), 'supplier_bill_match_results', ['purchase_order_line_item_id'], unique=False)
    op.create_index(op.f('ix_supplier_bill_match_results_status'), 'supplier_bill_match_results', ['status'], unique=False)
    op.create_index(op.f('ix_supplier_bill_match_results_supplier_bill_id'), 'supplier_bill_match_results', ['supplier_bill_id'], unique=False)
    op.create_index(op.f('ix_supplier_bill_match_results_supplier_bill_line_item_id'), 'supplier_bill_match_results', ['supplier_bill_line_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supplier_bill_match_results_supplier_bill_line_item_id'), table_name='supplier_bill_match_results')
    op.drop_index(op.f('ix_supplier_bill_match_results_supplier_bill_id'), table_name='supplier_bill_match_results')
    op.drop_index(op.f('ix_supplier_bill_match_results_status'), table_name='supplier_bill_match_results')
    op.drop_index(op.f('ix_supplier_bill_match_results_purchase_order_line_item_id'), table_name='supplier_bill_match_results')
    op.drop_index(op.f('ix_supplier_bill_match_results_evaluated_by_user_id'), table_name='supplier_bill_match_results')
    op.drop_index('ix_supplier_bill_match_results_bill_status', table_name='supplier_bill_match_results')
    op.drop_table('supplier_bill_match_results')
    op.drop_index('ix_supplier_bill_lines_bill_order_line', table_name='supplier_bill_line_items')
    op.drop_index(op.f('ix_supplier_bill_line_items_supplier_bill_id'), table_name='supplier_bill_line_items')
    op.drop_index(op.f('ix_supplier_bill_line_items_purchase_order_line_item_id'), table_name='supplier_bill_line_items')
    op.drop_table('supplier_bill_line_items')
    op.drop_index(op.f('ix_supplier_bills_voided_by_user_id'), table_name='supplier_bills')
    op.drop_index(op.f('ix_supplier_bills_supplier_invoice_number'), table_name='supplier_bills')
    op.drop_index(op.f('ix_supplier_bills_supplier_id'), table_name='supplier_bills')
    op.drop_index(op.f('ix_supplier_bills_submitted_by_user_id'), table_name='supplier_bills')
    op.drop_index(op.f('ix_supplier_bills_status'), table_name='supplier_bills')
    op.drop_index(op.f('ix_supplier_bills_purchase_order_id'), table_name='supplier_bills')
    op.drop_index('ix_supplier_bills_organization_supplier', table_name='supplier_bills')
    op.drop_index('ix_supplier_bills_organization_status', table_name='supplier_bills')
    op.drop_index('ix_supplier_bills_organization_purchase_order', table_name='supplier_bills')
    op.drop_index('ix_supplier_bills_organization_match_status', table_name='supplier_bills')
    op.drop_index('ix_supplier_bills_organization_invoice_date', table_name='supplier_bills')
    op.drop_index(op.f('ix_supplier_bills_organization_id'), table_name='supplier_bills')
    op.drop_index('ix_supplier_bills_organization_due_date', table_name='supplier_bills')
    op.drop_index('ix_supplier_bills_organization_active', table_name='supplier_bills')
    op.drop_index(op.f('ix_supplier_bills_matched_by_user_id'), table_name='supplier_bills')
    op.drop_index(op.f('ix_supplier_bills_match_status'), table_name='supplier_bills')
    op.drop_index(op.f('ix_supplier_bills_is_active'), table_name='supplier_bills')
    op.drop_index(op.f('ix_supplier_bills_invoice_date'), table_name='supplier_bills')
    op.drop_index(op.f('ix_supplier_bills_due_date'), table_name='supplier_bills')
    op.drop_index(op.f('ix_supplier_bills_currency'), table_name='supplier_bills')
    op.drop_index(op.f('ix_supplier_bills_created_by_user_id'), table_name='supplier_bills')
    op.drop_index(op.f('ix_supplier_bills_approved_by_user_id'), table_name='supplier_bills')
    op.drop_table('supplier_bills')
    # ### end Alembic commands ###
